// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : tul_pynq_z2.v
// Device     : xc7z020clg400-1
// LiteX sha1 : b9a1fec30
// Date       : 2025-11-04 13:44:47
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module tul_pynq_z2 (
	(* dont_touch = "true" *)	input  wire clk125,
	output reg  usb_uart_tx,
	input  wire usb_uart_rx,
	output wire user_led0,
	output wire user_led1,
	output wire user_led2,
	output wire user_led3,
	output wire to_reconfig,
	output wire [2:0]configure_to,
	output wire decouple_status,
	input wire decouple
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

reg  soc_crg_rst0 = 1'd0;
(* dont_touch = "true" *) wire sys_clk;
wire sys_rst;
wire soc_crg_reset;
reg  soc_crg_power_down = 1'd0;
wire soc_crg_locked;
(* dont_touch = "true" *) wire soc_crg_clkin;
wire soc_crg_clkout;
wire soc_crg_clkout_buf;
reg  soc_basesoc_soc_rst = 1'd0;
wire soc_basesoc_cpu_rst;
reg  [1:0] soc_basesoc_reset_storage = 2'd0;
reg  soc_basesoc_reset_re = 1'd0;
reg  [31:0] soc_basesoc_scratch_storage = 32'd305419896;
reg  soc_basesoc_scratch_re = 1'd0;
wire [31:0] soc_basesoc_bus_errors_status;
wire soc_basesoc_bus_errors_we;
reg  soc_basesoc_bus_errors_re = 1'd0;
wire soc_basesoc_bus_error;
reg  [31:0] soc_basesoc_bus_errors = 32'd0;
wire soc_basesoc_reset;
reg  [31:0] soc_basesoc_interrupt = 32'd0;
wire [29:0] soc_basesoc_ibus_adr;
wire [31:0] soc_basesoc_ibus_dat_w;
wire [31:0] soc_basesoc_ibus_dat_r;
wire [3:0] soc_basesoc_ibus_sel;
wire soc_basesoc_ibus_cyc;
wire soc_basesoc_ibus_stb;
wire soc_basesoc_ibus_ack;
wire soc_basesoc_ibus_we;
wire [2:0] soc_basesoc_ibus_cti;
wire [1:0] soc_basesoc_ibus_bte;
wire soc_basesoc_ibus_err;
wire [29:0] soc_basesoc_dbus_adr;
wire [31:0] soc_basesoc_dbus_dat_w;
wire [31:0] soc_basesoc_dbus_dat_r;
wire [3:0] soc_basesoc_dbus_sel;
wire soc_basesoc_dbus_cyc;
wire soc_basesoc_dbus_stb;
wire soc_basesoc_dbus_ack;
wire soc_basesoc_dbus_we;
wire [2:0] soc_basesoc_dbus_cti;
wire [1:0] soc_basesoc_dbus_bte;
wire soc_basesoc_dbus_err;
wire soc_basesoc_vexriscv_cfu_bus_cmd_valid;
wire soc_basesoc_vexriscv_cfu_bus_cmd_ready;
wire [9:0] soc_basesoc_vexriscv_cfu_bus_cmd_payload_function_id;
wire [31:0] soc_basesoc_vexriscv_cfu_bus_cmd_payload_inputs_0;
wire [31:0] soc_basesoc_vexriscv_cfu_bus_cmd_payload_inputs_1;
wire soc_basesoc_vexriscv_cfu_bus_rsp_valid;
wire soc_basesoc_vexriscv_cfu_bus_rsp_ready;
wire [31:0] soc_basesoc_vexriscv_cfu_bus_rsp_payload_outputs_0;
reg  [31:0] soc_basesoc_vexriscv = 32'd0;
wire [29:0] soc_basesoc_basesoc_ram_bus_adr;
wire [31:0] soc_basesoc_basesoc_ram_bus_dat_w;
wire [31:0] soc_basesoc_basesoc_ram_bus_dat_r;
wire [3:0] soc_basesoc_basesoc_ram_bus_sel;
wire soc_basesoc_basesoc_ram_bus_cyc;
wire soc_basesoc_basesoc_ram_bus_stb;
reg  soc_basesoc_basesoc_ram_bus_ack = 1'd0;
wire soc_basesoc_basesoc_ram_bus_we;
wire [2:0] soc_basesoc_basesoc_ram_bus_cti;
wire [1:0] soc_basesoc_basesoc_ram_bus_bte;
reg  soc_basesoc_basesoc_ram_bus_err = 1'd0;
reg  soc_basesoc_basesoc_adr_burst = 1'd0;
wire [14:0] soc_basesoc_basesoc_adr;
wire [31:0] soc_basesoc_basesoc_dat_r;
wire [29:0] soc_basesoc_ram_bus_ram_bus_adr;
wire [31:0] soc_basesoc_ram_bus_ram_bus_dat_w;
wire [31:0] soc_basesoc_ram_bus_ram_bus_dat_r;
wire [3:0] soc_basesoc_ram_bus_ram_bus_sel;
wire soc_basesoc_ram_bus_ram_bus_cyc;
wire soc_basesoc_ram_bus_ram_bus_stb;
reg  soc_basesoc_ram_bus_ram_bus_ack = 1'd0;
wire soc_basesoc_ram_bus_ram_bus_we;
wire [2:0] soc_basesoc_ram_bus_ram_bus_cti;
wire [1:0] soc_basesoc_ram_bus_ram_bus_bte;
reg  soc_basesoc_ram_bus_ram_bus_err = 1'd0;
reg  soc_basesoc_ram_adr_burst = 1'd0;
wire [10:0] soc_basesoc_ram_adr;
wire [31:0] soc_basesoc_ram_dat_r;
reg  [3:0] soc_basesoc_ram_we = 4'd0;
wire [31:0] soc_basesoc_ram_dat_w;
wire soc_basesoc_tx_sink_valid;
reg  soc_basesoc_tx_sink_ready = 1'd0;
wire soc_basesoc_tx_sink_first;
wire soc_basesoc_tx_sink_last;
wire [7:0] soc_basesoc_tx_sink_payload_data;
reg  [7:0] soc_basesoc_tx_data = 8'd0;
reg  [3:0] soc_basesoc_tx_count = 4'd0;
reg  soc_basesoc_tx_enable = 1'd0;
reg  soc_basesoc_tx_tick = 1'd0;
reg  [31:0] soc_basesoc_tx_phase = 32'd0;
reg  soc_basesoc_rx_source_valid = 1'd0;
wire soc_basesoc_rx_source_ready;
reg  soc_basesoc_rx_source_first = 1'd0;
reg  soc_basesoc_rx_source_last = 1'd0;
reg  [7:0] soc_basesoc_rx_source_payload_data = 8'd0;
reg  [7:0] soc_basesoc_rx_data = 8'd0;
reg  [3:0] soc_basesoc_rx_count = 4'd0;
reg  soc_basesoc_rx_enable = 1'd0;
reg  soc_basesoc_rx_tick = 1'd0;
reg  [31:0] soc_basesoc_rx_phase = 32'd0;
wire soc_basesoc_rx_rx;
reg  soc_basesoc_rx_rx_d = 1'd0;
reg  soc_basesoc_uart_rxtx_re = 1'd0;
wire [7:0] soc_basesoc_uart_rxtx_r;
reg  soc_basesoc_uart_rxtx_we = 1'd0;
wire [7:0] soc_basesoc_uart_rxtx_w;
wire soc_basesoc_uart_txfull_status;
wire soc_basesoc_uart_txfull_we;
reg  soc_basesoc_uart_txfull_re = 1'd0;
wire soc_basesoc_uart_rxempty_status;
wire soc_basesoc_uart_rxempty_we;
reg  soc_basesoc_uart_rxempty_re = 1'd0;
wire soc_basesoc_uart_irq;
wire soc_basesoc_uart_tx_status;
reg  soc_basesoc_uart_tx_pending = 1'd0;
wire soc_basesoc_uart_tx_trigger;
reg  soc_basesoc_uart_tx_clear = 1'd0;
reg  soc_basesoc_uart_tx_trigger_d = 1'd0;
wire soc_basesoc_uart_rx_status;
reg  soc_basesoc_uart_rx_pending = 1'd0;
wire soc_basesoc_uart_rx_trigger;
reg  soc_basesoc_uart_rx_clear = 1'd0;
reg  soc_basesoc_uart_rx_trigger_d = 1'd0;
wire soc_basesoc_uart_tx0;
wire soc_basesoc_uart_rx0;
reg  [1:0] soc_basesoc_uart_status_status = 2'd0;
wire soc_basesoc_uart_status_we;
reg  soc_basesoc_uart_status_re = 1'd0;
wire soc_basesoc_uart_tx1;
wire soc_basesoc_uart_rx1;
reg  [1:0] soc_basesoc_uart_pending_status = 2'd0;
wire soc_basesoc_uart_pending_we;
reg  soc_basesoc_uart_pending_re = 1'd0;
reg  [1:0] soc_basesoc_uart_pending_r = 2'd0;
wire soc_basesoc_uart_tx2;
wire soc_basesoc_uart_rx2;
reg  [1:0] soc_basesoc_uart_enable_storage = 2'd0;
reg  soc_basesoc_uart_enable_re = 1'd0;
wire soc_basesoc_uart_txempty_status;
wire soc_basesoc_uart_txempty_we;
reg  soc_basesoc_uart_txempty_re = 1'd0;
wire soc_basesoc_uart_rxfull_status;
wire soc_basesoc_uart_rxfull_we;
reg  soc_basesoc_uart_rxfull_re = 1'd0;
wire soc_basesoc_uart_uart_sink_valid;
wire soc_basesoc_uart_uart_sink_ready;
wire soc_basesoc_uart_uart_sink_first;
wire soc_basesoc_uart_uart_sink_last;
wire [7:0] soc_basesoc_uart_uart_sink_payload_data;
wire soc_basesoc_uart_uart_source_valid;
wire soc_basesoc_uart_uart_source_ready;
wire soc_basesoc_uart_uart_source_first;
wire soc_basesoc_uart_uart_source_last;
wire [7:0] soc_basesoc_uart_uart_source_payload_data;
wire soc_basesoc_uart_tx_fifo_sink_valid;
wire soc_basesoc_uart_tx_fifo_sink_ready;
reg  soc_basesoc_uart_tx_fifo_sink_first = 1'd0;
reg  soc_basesoc_uart_tx_fifo_sink_last = 1'd0;
wire [7:0] soc_basesoc_uart_tx_fifo_sink_payload_data;
wire soc_basesoc_uart_tx_fifo_source_valid;
wire soc_basesoc_uart_tx_fifo_source_ready;
wire soc_basesoc_uart_tx_fifo_source_first;
wire soc_basesoc_uart_tx_fifo_source_last;
wire [7:0] soc_basesoc_uart_tx_fifo_source_payload_data;
wire soc_basesoc_uart_tx_fifo_re;
reg  soc_basesoc_uart_tx_fifo_readable = 1'd0;
wire soc_basesoc_uart_tx_fifo_syncfifo_we;
wire soc_basesoc_uart_tx_fifo_syncfifo_writable;
wire soc_basesoc_uart_tx_fifo_syncfifo_re;
wire soc_basesoc_uart_tx_fifo_syncfifo_readable;
wire [9:0] soc_basesoc_uart_tx_fifo_syncfifo_din;
wire [9:0] soc_basesoc_uart_tx_fifo_syncfifo_dout;
reg  [4:0] soc_basesoc_uart_tx_fifo_level0 = 5'd0;
reg  soc_basesoc_uart_tx_fifo_replace = 1'd0;
reg  [3:0] soc_basesoc_uart_tx_fifo_produce = 4'd0;
reg  [3:0] soc_basesoc_uart_tx_fifo_consume = 4'd0;
reg  [3:0] soc_basesoc_uart_tx_fifo_wrport_adr = 4'd0;
wire [9:0] soc_basesoc_uart_tx_fifo_wrport_dat_r;
wire soc_basesoc_uart_tx_fifo_wrport_we;
wire [9:0] soc_basesoc_uart_tx_fifo_wrport_dat_w;
wire soc_basesoc_uart_tx_fifo_do_read;
wire [3:0] soc_basesoc_uart_tx_fifo_rdport_adr;
wire [9:0] soc_basesoc_uart_tx_fifo_rdport_dat_r;
wire soc_basesoc_uart_tx_fifo_rdport_re;
wire [4:0] soc_basesoc_uart_tx_fifo_level1;
wire [7:0] soc_basesoc_uart_tx_fifo_fifo_in_payload_data;
wire soc_basesoc_uart_tx_fifo_fifo_in_first;
wire soc_basesoc_uart_tx_fifo_fifo_in_last;
wire [7:0] soc_basesoc_uart_tx_fifo_fifo_out_payload_data;
wire soc_basesoc_uart_tx_fifo_fifo_out_first;
wire soc_basesoc_uart_tx_fifo_fifo_out_last;
wire soc_basesoc_uart_rx_fifo_sink_valid;
wire soc_basesoc_uart_rx_fifo_sink_ready;
wire soc_basesoc_uart_rx_fifo_sink_first;
wire soc_basesoc_uart_rx_fifo_sink_last;
wire [7:0] soc_basesoc_uart_rx_fifo_sink_payload_data;
wire soc_basesoc_uart_rx_fifo_source_valid;
wire soc_basesoc_uart_rx_fifo_source_ready;
wire soc_basesoc_uart_rx_fifo_source_first;
wire soc_basesoc_uart_rx_fifo_source_last;
wire [7:0] soc_basesoc_uart_rx_fifo_source_payload_data;
wire soc_basesoc_uart_rx_fifo_re;
reg  soc_basesoc_uart_rx_fifo_readable = 1'd0;
wire soc_basesoc_uart_rx_fifo_syncfifo_we;
wire soc_basesoc_uart_rx_fifo_syncfifo_writable;
wire soc_basesoc_uart_rx_fifo_syncfifo_re;
wire soc_basesoc_uart_rx_fifo_syncfifo_readable;
wire [9:0] soc_basesoc_uart_rx_fifo_syncfifo_din;
wire [9:0] soc_basesoc_uart_rx_fifo_syncfifo_dout;
reg  [4:0] soc_basesoc_uart_rx_fifo_level0 = 5'd0;
reg  soc_basesoc_uart_rx_fifo_replace = 1'd0;
reg  [3:0] soc_basesoc_uart_rx_fifo_produce = 4'd0;
reg  [3:0] soc_basesoc_uart_rx_fifo_consume = 4'd0;
reg  [3:0] soc_basesoc_uart_rx_fifo_wrport_adr = 4'd0;
wire [9:0] soc_basesoc_uart_rx_fifo_wrport_dat_r;
wire soc_basesoc_uart_rx_fifo_wrport_we;
wire [9:0] soc_basesoc_uart_rx_fifo_wrport_dat_w;
wire soc_basesoc_uart_rx_fifo_do_read;
wire [3:0] soc_basesoc_uart_rx_fifo_rdport_adr;
wire [9:0] soc_basesoc_uart_rx_fifo_rdport_dat_r;
wire soc_basesoc_uart_rx_fifo_rdport_re;
wire [4:0] soc_basesoc_uart_rx_fifo_level1;
wire [7:0] soc_basesoc_uart_rx_fifo_fifo_in_payload_data;
wire soc_basesoc_uart_rx_fifo_fifo_in_first;
wire soc_basesoc_uart_rx_fifo_fifo_in_last;
wire [7:0] soc_basesoc_uart_rx_fifo_fifo_out_payload_data;
wire soc_basesoc_uart_rx_fifo_fifo_out_first;
wire soc_basesoc_uart_rx_fifo_fifo_out_last;
reg  [31:0] soc_basesoc_timer_load_storage = 32'd0;
reg  soc_basesoc_timer_load_re = 1'd0;
reg  [31:0] soc_basesoc_timer_reload_storage = 32'd0;
reg  soc_basesoc_timer_reload_re = 1'd0;
reg  soc_basesoc_timer_en_storage = 1'd0;
reg  soc_basesoc_timer_en_re = 1'd0;
reg  soc_basesoc_timer_update_value_storage = 1'd0;
reg  soc_basesoc_timer_update_value_re = 1'd0;
reg  [31:0] soc_basesoc_timer_value_status = 32'd0;
wire soc_basesoc_timer_value_we;
reg  soc_basesoc_timer_value_re = 1'd0;
wire soc_basesoc_timer_irq;
wire soc_basesoc_timer_zero_status;
reg  soc_basesoc_timer_zero_pending = 1'd0;
wire soc_basesoc_timer_zero_trigger;
reg  soc_basesoc_timer_zero_clear = 1'd0;
reg  soc_basesoc_timer_zero_trigger_d = 1'd0;
wire soc_basesoc_timer_zero0;
wire soc_basesoc_timer_status_status;
wire soc_basesoc_timer_status_we;
reg  soc_basesoc_timer_status_re = 1'd0;
wire soc_basesoc_timer_zero1;
wire soc_basesoc_timer_pending_status;
wire soc_basesoc_timer_pending_we;
reg  soc_basesoc_timer_pending_re = 1'd0;
reg  soc_basesoc_timer_pending_r = 1'd0;
wire soc_basesoc_timer_zero2;
reg  soc_basesoc_timer_enable_storage = 1'd0;
reg  soc_basesoc_timer_enable_re = 1'd0;
reg  [31:0] soc_basesoc_timer_value = 32'd0;
reg  [3:0] soc_storage = 4'd0;
reg  soc_re = 1'd0;
reg  [3:0] soc_chaser = 4'd0;
reg  soc_mode = 1'd0;
wire soc_wait;
wire soc_done;
reg  [23:0] soc_count = 24'd12500000;
reg  [3:0] soc_leds = 4'd0;
reg  [13:0] soc_builder_basesoc_adr = 14'd0;
reg  soc_builder_basesoc_we = 1'd0;
reg  [31:0] soc_builder_basesoc_dat_w = 32'd0;
wire [31:0] soc_builder_basesoc_dat_r;
wire [29:0] soc_builder_basesoc_wishbone_adr;
wire [31:0] soc_builder_basesoc_wishbone_dat_w;
reg  [31:0] soc_builder_basesoc_wishbone_dat_r = 32'd0;
wire [3:0] soc_builder_basesoc_wishbone_sel;
wire soc_builder_basesoc_wishbone_cyc;
wire soc_builder_basesoc_wishbone_stb;
reg  soc_builder_basesoc_wishbone_ack = 1'd0;
wire soc_builder_basesoc_wishbone_we;
wire [2:0] soc_builder_basesoc_wishbone_cti;
wire [1:0] soc_builder_basesoc_wishbone_bte;
reg  soc_builder_basesoc_wishbone_err = 1'd0;
wire [29:0] soc_builder_shared_adr;
wire [31:0] soc_builder_shared_dat_w;
reg  [31:0] soc_builder_shared_dat_r = 32'd0;
wire [3:0] soc_builder_shared_sel;
wire soc_builder_shared_cyc;
wire soc_builder_shared_stb;
reg  soc_builder_shared_ack = 1'd0;
wire soc_builder_shared_we;
wire [2:0] soc_builder_shared_cti;
wire [1:0] soc_builder_shared_bte;
wire soc_builder_shared_err;
wire [1:0] soc_builder_request;
reg  soc_builder_grant = 1'd0;
reg  [2:0] soc_builder_slave_sel = 3'd0;
reg  [2:0] soc_builder_slave_sel_r = 3'd0;
reg  soc_builder_error = 1'd0;
wire soc_builder_wait;
wire soc_builder_done;
reg  [19:0] soc_builder_count = 20'd1000000;
wire [13:0] soc_builder_csr_bankarray_interface0_bank_bus_adr;
wire soc_builder_csr_bankarray_interface0_bank_bus_we;
wire [31:0] soc_builder_csr_bankarray_interface0_bank_bus_dat_w;
reg  [31:0] soc_builder_csr_bankarray_interface0_bank_bus_dat_r = 32'd0;
reg  soc_builder_csr_bankarray_csrbank0_reset0_re = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank0_reset0_r;
reg  soc_builder_csr_bankarray_csrbank0_reset0_we = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank0_reset0_w;
reg  soc_builder_csr_bankarray_csrbank0_scratch0_re = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank0_scratch0_r;
reg  soc_builder_csr_bankarray_csrbank0_scratch0_we = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank0_scratch0_w;
reg  soc_builder_csr_bankarray_csrbank0_bus_errors_re = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank0_bus_errors_r;
reg  soc_builder_csr_bankarray_csrbank0_bus_errors_we = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank0_bus_errors_w;
wire soc_builder_csr_bankarray_csrbank0_sel;
wire [13:0] soc_builder_csr_bankarray_sram_bus_adr;
wire soc_builder_csr_bankarray_sram_bus_we;
wire [31:0] soc_builder_csr_bankarray_sram_bus_dat_w;
reg  [31:0] soc_builder_csr_bankarray_sram_bus_dat_r = 32'd0;
wire [5:0] soc_builder_csr_bankarray_adr;
wire [7:0] soc_builder_csr_bankarray_dat_r;
wire soc_builder_csr_bankarray_sel;
reg  soc_builder_csr_bankarray_sel_r = 1'd0;
wire [13:0] soc_builder_csr_bankarray_interface1_bank_bus_adr;
wire soc_builder_csr_bankarray_interface1_bank_bus_we;
wire [31:0] soc_builder_csr_bankarray_interface1_bank_bus_dat_w;
reg  [31:0] soc_builder_csr_bankarray_interface1_bank_bus_dat_r = 32'd0;
reg  soc_builder_csr_bankarray_csrbank1_out0_re = 1'd0;
wire [3:0] soc_builder_csr_bankarray_csrbank1_out0_r;
reg  soc_builder_csr_bankarray_csrbank1_out0_we = 1'd0;
wire [3:0] soc_builder_csr_bankarray_csrbank1_out0_w;
wire soc_builder_csr_bankarray_csrbank1_sel;
wire [13:0] soc_builder_csr_bankarray_interface2_bank_bus_adr;
wire soc_builder_csr_bankarray_interface2_bank_bus_we;
wire [31:0] soc_builder_csr_bankarray_interface2_bank_bus_dat_w;
reg  [31:0] soc_builder_csr_bankarray_interface2_bank_bus_dat_r = 32'd0;
reg  soc_builder_csr_bankarray_csrbank2_load0_re = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank2_load0_r;
reg  soc_builder_csr_bankarray_csrbank2_load0_we = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank2_load0_w;
reg  soc_builder_csr_bankarray_csrbank2_reload0_re = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank2_reload0_r;
reg  soc_builder_csr_bankarray_csrbank2_reload0_we = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank2_reload0_w;
reg  soc_builder_csr_bankarray_csrbank2_en0_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_en0_r;
reg  soc_builder_csr_bankarray_csrbank2_en0_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_en0_w;
reg  soc_builder_csr_bankarray_csrbank2_update_value0_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_update_value0_r;
reg  soc_builder_csr_bankarray_csrbank2_update_value0_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_update_value0_w;
reg  soc_builder_csr_bankarray_csrbank2_value_re = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank2_value_r;
reg  soc_builder_csr_bankarray_csrbank2_value_we = 1'd0;
wire [31:0] soc_builder_csr_bankarray_csrbank2_value_w;
reg  soc_builder_csr_bankarray_csrbank2_ev_status_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_ev_status_r;
reg  soc_builder_csr_bankarray_csrbank2_ev_status_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_ev_status_w;
reg  soc_builder_csr_bankarray_csrbank2_ev_pending_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_ev_pending_r;
reg  soc_builder_csr_bankarray_csrbank2_ev_pending_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_ev_pending_w;
reg  soc_builder_csr_bankarray_csrbank2_ev_enable0_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_ev_enable0_r;
reg  soc_builder_csr_bankarray_csrbank2_ev_enable0_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank2_ev_enable0_w;
wire soc_builder_csr_bankarray_csrbank2_sel;
wire [13:0] soc_builder_csr_bankarray_interface3_bank_bus_adr;
wire soc_builder_csr_bankarray_interface3_bank_bus_we;
wire [31:0] soc_builder_csr_bankarray_interface3_bank_bus_dat_w;
reg  [31:0] soc_builder_csr_bankarray_interface3_bank_bus_dat_r = 32'd0;
reg  soc_builder_csr_bankarray_csrbank3_txfull_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_txfull_r;
reg  soc_builder_csr_bankarray_csrbank3_txfull_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_txfull_w;
reg  soc_builder_csr_bankarray_csrbank3_rxempty_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_rxempty_r;
reg  soc_builder_csr_bankarray_csrbank3_rxempty_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_rxempty_w;
reg  soc_builder_csr_bankarray_csrbank3_ev_status_re = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank3_ev_status_r;
reg  soc_builder_csr_bankarray_csrbank3_ev_status_we = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank3_ev_status_w;
reg  soc_builder_csr_bankarray_csrbank3_ev_pending_re = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank3_ev_pending_r;
reg  soc_builder_csr_bankarray_csrbank3_ev_pending_we = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank3_ev_pending_w;
reg  soc_builder_csr_bankarray_csrbank3_ev_enable0_re = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank3_ev_enable0_r;
reg  soc_builder_csr_bankarray_csrbank3_ev_enable0_we = 1'd0;
wire [1:0] soc_builder_csr_bankarray_csrbank3_ev_enable0_w;
reg  soc_builder_csr_bankarray_csrbank3_txempty_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_txempty_r;
reg  soc_builder_csr_bankarray_csrbank3_txempty_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_txempty_w;
reg  soc_builder_csr_bankarray_csrbank3_rxfull_re = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_rxfull_r;
reg  soc_builder_csr_bankarray_csrbank3_rxfull_we = 1'd0;
wire soc_builder_csr_bankarray_csrbank3_rxfull_w;
wire soc_builder_csr_bankarray_csrbank3_sel;
wire [13:0] soc_builder_csr_interconnect_adr;
wire soc_builder_csr_interconnect_we;
wire [31:0] soc_builder_csr_interconnect_dat_w;
wire [31:0] soc_builder_csr_interconnect_dat_r;
wire soc_builder_basesoc_reset0;
wire soc_builder_basesoc_reset1;
wire soc_builder_basesoc_reset2;
wire soc_builder_basesoc_reset3;
wire soc_builder_basesoc_reset4;
wire soc_builder_basesoc_reset5;
wire soc_builder_basesoc_reset6;
wire soc_builder_basesoc_reset7;
wire soc_builder_basesoc_pll_fb;
reg  soc_builder_basesoc_rs232phytx_state = 1'd0;
reg  soc_builder_basesoc_rs232phytx_next_state = 1'd0;
reg  [3:0] soc_basesoc_tx_count_rs232phytx_next_value0 = 4'd0;
reg  soc_basesoc_tx_count_rs232phytx_next_value_ce0 = 1'd0;
reg  soc_basesoc_usb_uart_tx_rs232phytx_next_value1 = 1'd0;
reg  soc_basesoc_usb_uart_tx_rs232phytx_next_value_ce1 = 1'd0;
reg  [7:0] soc_basesoc_tx_data_rs232phytx_next_value2 = 8'd0;
reg  soc_basesoc_tx_data_rs232phytx_next_value_ce2 = 1'd0;
reg  soc_builder_basesoc_rs232phyrx_state = 1'd0;
reg  soc_builder_basesoc_rs232phyrx_next_state = 1'd0;
reg  [3:0] soc_basesoc_rx_count_rs232phyrx_next_value0 = 4'd0;
reg  soc_basesoc_rx_count_rs232phyrx_next_value_ce0 = 1'd0;
reg  [7:0] soc_basesoc_rx_data_rs232phyrx_next_value1 = 8'd0;
reg  soc_basesoc_rx_data_rs232phyrx_next_value_ce1 = 1'd0;
reg  soc_builder_basesoc_state = 1'd0;
reg  soc_builder_basesoc_next_state = 1'd0;
reg  [29:0] soc_builder_array_muxed0 = 30'd0;
reg  [31:0] soc_builder_array_muxed1 = 32'd0;
reg  [3:0] soc_builder_array_muxed2 = 4'd0;
reg  soc_builder_array_muxed3 = 1'd0;
reg  soc_builder_array_muxed4 = 1'd0;
reg  soc_builder_array_muxed5 = 1'd0;
reg  [2:0] soc_builder_array_muxed6 = 3'd0;
reg  [1:0] soc_builder_array_muxed7 = 2'd0;
wire soc_builder_xilinxasyncresetsynchronizerimpl;
wire soc_builder_xilinxasyncresetsynchronizerimpl_rst_meta;
(* async_reg = "true", mr_ff = "true", dont_touch = "true" *) reg  soc_builder_regs0 = 1'd0;
(* async_reg = "true", dont_touch = "true" *) reg  soc_builder_regs1 = 1'd0;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign soc_basesoc_reset = (soc_basesoc_soc_rst | soc_basesoc_cpu_rst);
always @(*) begin
	soc_crg_rst0 <= 1'd0;
	if (soc_basesoc_soc_rst) begin
		soc_crg_rst0 <= 1'd1;
	end
end
assign soc_basesoc_bus_error = soc_builder_error;
always @(*) begin
	soc_basesoc_interrupt <= 32'd0;
	soc_basesoc_interrupt[1] <= soc_basesoc_timer_irq;
	soc_basesoc_interrupt[0] <= soc_basesoc_uart_irq;
end
assign soc_crg_reset = soc_crg_rst0;
assign soc_crg_clkin = clk125;
assign sys_clk = soc_crg_clkout_buf;
assign soc_basesoc_bus_errors_status = soc_basesoc_bus_errors;
assign soc_basesoc_basesoc_adr = soc_basesoc_basesoc_ram_bus_adr[14:0];
assign soc_basesoc_basesoc_ram_bus_dat_r = soc_basesoc_basesoc_dat_r;
always @(*) begin
	soc_basesoc_ram_we <= 4'd0;
	soc_basesoc_ram_we[0] <= (((soc_basesoc_ram_bus_ram_bus_cyc & soc_basesoc_ram_bus_ram_bus_stb) & soc_basesoc_ram_bus_ram_bus_we) & soc_basesoc_ram_bus_ram_bus_sel[0]);
	soc_basesoc_ram_we[1] <= (((soc_basesoc_ram_bus_ram_bus_cyc & soc_basesoc_ram_bus_ram_bus_stb) & soc_basesoc_ram_bus_ram_bus_we) & soc_basesoc_ram_bus_ram_bus_sel[1]);
	soc_basesoc_ram_we[2] <= (((soc_basesoc_ram_bus_ram_bus_cyc & soc_basesoc_ram_bus_ram_bus_stb) & soc_basesoc_ram_bus_ram_bus_we) & soc_basesoc_ram_bus_ram_bus_sel[2]);
	soc_basesoc_ram_we[3] <= (((soc_basesoc_ram_bus_ram_bus_cyc & soc_basesoc_ram_bus_ram_bus_stb) & soc_basesoc_ram_bus_ram_bus_we) & soc_basesoc_ram_bus_ram_bus_sel[3]);
end
assign soc_basesoc_ram_adr = soc_basesoc_ram_bus_ram_bus_adr[10:0];
assign soc_basesoc_ram_bus_ram_bus_dat_r = soc_basesoc_ram_dat_r;
assign soc_basesoc_ram_dat_w = soc_basesoc_ram_bus_ram_bus_dat_w;
always @(*) begin
	soc_builder_basesoc_rs232phytx_next_state <= 1'd0;
	soc_basesoc_tx_count_rs232phytx_next_value0 <= 4'd0;
	soc_basesoc_tx_count_rs232phytx_next_value_ce0 <= 1'd0;
	soc_basesoc_usb_uart_tx_rs232phytx_next_value1 <= 1'd0;
	soc_basesoc_usb_uart_tx_rs232phytx_next_value_ce1 <= 1'd0;
	soc_basesoc_tx_sink_ready <= 1'd0;
	soc_basesoc_tx_data_rs232phytx_next_value2 <= 8'd0;
	soc_basesoc_tx_data_rs232phytx_next_value_ce2 <= 1'd0;
	soc_basesoc_tx_enable <= 1'd0;
	soc_builder_basesoc_rs232phytx_next_state <= soc_builder_basesoc_rs232phytx_state;
	case (soc_builder_basesoc_rs232phytx_state)
		1'd1: begin
			soc_basesoc_tx_enable <= 1'd1;
			if (soc_basesoc_tx_tick) begin
				soc_basesoc_usb_uart_tx_rs232phytx_next_value1 <= soc_basesoc_tx_data;
				soc_basesoc_usb_uart_tx_rs232phytx_next_value_ce1 <= 1'd1;
				soc_basesoc_tx_count_rs232phytx_next_value0 <= (soc_basesoc_tx_count + 1'd1);
				soc_basesoc_tx_count_rs232phytx_next_value_ce0 <= 1'd1;
				soc_basesoc_tx_data_rs232phytx_next_value2 <= {1'd1, soc_basesoc_tx_data[7:1]};
				soc_basesoc_tx_data_rs232phytx_next_value_ce2 <= 1'd1;
				if ((soc_basesoc_tx_count == 4'd9)) begin
					soc_basesoc_tx_sink_ready <= 1'd1;
					soc_builder_basesoc_rs232phytx_next_state <= 1'd0;
				end
			end
		end
		default: begin
			soc_basesoc_tx_count_rs232phytx_next_value0 <= 1'd0;
			soc_basesoc_tx_count_rs232phytx_next_value_ce0 <= 1'd1;
			soc_basesoc_usb_uart_tx_rs232phytx_next_value1 <= 1'd1;
			soc_basesoc_usb_uart_tx_rs232phytx_next_value_ce1 <= 1'd1;
			if (soc_basesoc_tx_sink_valid) begin
				soc_basesoc_usb_uart_tx_rs232phytx_next_value1 <= 1'd0;
				soc_basesoc_usb_uart_tx_rs232phytx_next_value_ce1 <= 1'd1;
				soc_basesoc_tx_data_rs232phytx_next_value2 <= soc_basesoc_tx_sink_payload_data;
				soc_basesoc_tx_data_rs232phytx_next_value_ce2 <= 1'd1;
				soc_builder_basesoc_rs232phytx_next_state <= 1'd1;
			end
		end
	endcase
end
always @(*) begin
	soc_basesoc_rx_enable <= 1'd0;
	soc_builder_basesoc_rs232phyrx_next_state <= 1'd0;
	soc_basesoc_rx_count_rs232phyrx_next_value0 <= 4'd0;
	soc_basesoc_rx_count_rs232phyrx_next_value_ce0 <= 1'd0;
	soc_basesoc_rx_source_valid <= 1'd0;
	soc_basesoc_rx_data_rs232phyrx_next_value1 <= 8'd0;
	soc_basesoc_rx_data_rs232phyrx_next_value_ce1 <= 1'd0;
	soc_basesoc_rx_source_payload_data <= 8'd0;
	soc_builder_basesoc_rs232phyrx_next_state <= soc_builder_basesoc_rs232phyrx_state;
	case (soc_builder_basesoc_rs232phyrx_state)
		1'd1: begin
			soc_basesoc_rx_enable <= 1'd1;
			if (soc_basesoc_rx_tick) begin
				soc_basesoc_rx_count_rs232phyrx_next_value0 <= (soc_basesoc_rx_count + 1'd1);
				soc_basesoc_rx_count_rs232phyrx_next_value_ce0 <= 1'd1;
				soc_basesoc_rx_data_rs232phyrx_next_value1 <= {soc_basesoc_rx_rx, soc_basesoc_rx_data[7:1]};
				soc_basesoc_rx_data_rs232phyrx_next_value_ce1 <= 1'd1;
				if ((soc_basesoc_rx_count == 4'd9)) begin
					soc_basesoc_rx_source_valid <= (soc_basesoc_rx_rx == 1'd1);
					soc_basesoc_rx_source_payload_data <= soc_basesoc_rx_data;
					soc_builder_basesoc_rs232phyrx_next_state <= 1'd0;
				end
			end
		end
		default: begin
			soc_basesoc_rx_count_rs232phyrx_next_value0 <= 1'd0;
			soc_basesoc_rx_count_rs232phyrx_next_value_ce0 <= 1'd1;
			if (((soc_basesoc_rx_rx == 1'd0) & (soc_basesoc_rx_rx_d == 1'd1))) begin
				soc_builder_basesoc_rs232phyrx_next_state <= 1'd1;
			end
		end
	endcase
end
assign soc_basesoc_uart_uart_sink_valid = soc_basesoc_rx_source_valid;
assign soc_basesoc_rx_source_ready = soc_basesoc_uart_uart_sink_ready;
assign soc_basesoc_uart_uart_sink_first = soc_basesoc_rx_source_first;
assign soc_basesoc_uart_uart_sink_last = soc_basesoc_rx_source_last;
assign soc_basesoc_uart_uart_sink_payload_data = soc_basesoc_rx_source_payload_data;
assign soc_basesoc_tx_sink_valid = soc_basesoc_uart_uart_source_valid;
assign soc_basesoc_uart_uart_source_ready = soc_basesoc_tx_sink_ready;
assign soc_basesoc_tx_sink_first = soc_basesoc_uart_uart_source_first;
assign soc_basesoc_tx_sink_last = soc_basesoc_uart_uart_source_last;
assign soc_basesoc_tx_sink_payload_data = soc_basesoc_uart_uart_source_payload_data;
assign soc_basesoc_uart_tx_fifo_sink_valid = soc_basesoc_uart_rxtx_re;
assign soc_basesoc_uart_tx_fifo_sink_payload_data = soc_basesoc_uart_rxtx_r;
assign soc_basesoc_uart_uart_source_valid = soc_basesoc_uart_tx_fifo_source_valid;
assign soc_basesoc_uart_tx_fifo_source_ready = soc_basesoc_uart_uart_source_ready;
assign soc_basesoc_uart_uart_source_first = soc_basesoc_uart_tx_fifo_source_first;
assign soc_basesoc_uart_uart_source_last = soc_basesoc_uart_tx_fifo_source_last;
assign soc_basesoc_uart_uart_source_payload_data = soc_basesoc_uart_tx_fifo_source_payload_data;
assign soc_basesoc_uart_txfull_status = (~soc_basesoc_uart_tx_fifo_sink_ready);
assign soc_basesoc_uart_txempty_status = (~soc_basesoc_uart_tx_fifo_source_valid);
assign soc_basesoc_uart_tx_trigger = soc_basesoc_uart_tx_fifo_sink_ready;
assign soc_basesoc_uart_rx_fifo_sink_valid = soc_basesoc_uart_uart_sink_valid;
assign soc_basesoc_uart_uart_sink_ready = soc_basesoc_uart_rx_fifo_sink_ready;
assign soc_basesoc_uart_rx_fifo_sink_first = soc_basesoc_uart_uart_sink_first;
assign soc_basesoc_uart_rx_fifo_sink_last = soc_basesoc_uart_uart_sink_last;
assign soc_basesoc_uart_rx_fifo_sink_payload_data = soc_basesoc_uart_uart_sink_payload_data;
assign soc_basesoc_uart_rxtx_w = soc_basesoc_uart_rx_fifo_source_payload_data;
assign soc_basesoc_uart_rx_fifo_source_ready = (soc_basesoc_uart_rx_clear | (1'd0 & soc_basesoc_uart_rxtx_we));
assign soc_basesoc_uart_rxempty_status = (~soc_basesoc_uart_rx_fifo_source_valid);
assign soc_basesoc_uart_rxfull_status = (~soc_basesoc_uart_rx_fifo_sink_ready);
assign soc_basesoc_uart_rx_trigger = soc_basesoc_uart_rx_fifo_source_valid;
assign soc_basesoc_uart_tx0 = soc_basesoc_uart_tx_status;
assign soc_basesoc_uart_tx1 = soc_basesoc_uart_tx_pending;
always @(*) begin
	soc_basesoc_uart_tx_clear <= 1'd0;
	if ((soc_basesoc_uart_pending_re & soc_basesoc_uart_pending_r[0])) begin
		soc_basesoc_uart_tx_clear <= 1'd1;
	end
end
assign soc_basesoc_uart_rx0 = soc_basesoc_uart_rx_status;
assign soc_basesoc_uart_rx1 = soc_basesoc_uart_rx_pending;
always @(*) begin
	soc_basesoc_uart_rx_clear <= 1'd0;
	if ((soc_basesoc_uart_pending_re & soc_basesoc_uart_pending_r[1])) begin
		soc_basesoc_uart_rx_clear <= 1'd1;
	end
end
assign soc_basesoc_uart_irq = ((soc_basesoc_uart_pending_status[0] & soc_basesoc_uart_enable_storage[0]) | (soc_basesoc_uart_pending_status[1] & soc_basesoc_uart_enable_storage[1]));
assign soc_basesoc_uart_tx_status = soc_basesoc_uart_tx_trigger;
assign soc_basesoc_uart_rx_status = soc_basesoc_uart_rx_trigger;
assign soc_basesoc_uart_tx_fifo_syncfifo_din = {soc_basesoc_uart_tx_fifo_fifo_in_last, soc_basesoc_uart_tx_fifo_fifo_in_first, soc_basesoc_uart_tx_fifo_fifo_in_payload_data};
assign {soc_basesoc_uart_tx_fifo_fifo_out_last, soc_basesoc_uart_tx_fifo_fifo_out_first, soc_basesoc_uart_tx_fifo_fifo_out_payload_data} = soc_basesoc_uart_tx_fifo_syncfifo_dout;
assign soc_basesoc_uart_tx_fifo_sink_ready = soc_basesoc_uart_tx_fifo_syncfifo_writable;
assign soc_basesoc_uart_tx_fifo_syncfifo_we = soc_basesoc_uart_tx_fifo_sink_valid;
assign soc_basesoc_uart_tx_fifo_fifo_in_first = soc_basesoc_uart_tx_fifo_sink_first;
assign soc_basesoc_uart_tx_fifo_fifo_in_last = soc_basesoc_uart_tx_fifo_sink_last;
assign soc_basesoc_uart_tx_fifo_fifo_in_payload_data = soc_basesoc_uart_tx_fifo_sink_payload_data;
assign soc_basesoc_uart_tx_fifo_source_valid = soc_basesoc_uart_tx_fifo_readable;
assign soc_basesoc_uart_tx_fifo_source_first = soc_basesoc_uart_tx_fifo_fifo_out_first;
assign soc_basesoc_uart_tx_fifo_source_last = soc_basesoc_uart_tx_fifo_fifo_out_last;
assign soc_basesoc_uart_tx_fifo_source_payload_data = soc_basesoc_uart_tx_fifo_fifo_out_payload_data;
assign soc_basesoc_uart_tx_fifo_re = soc_basesoc_uart_tx_fifo_source_ready;
assign soc_basesoc_uart_tx_fifo_syncfifo_re = (soc_basesoc_uart_tx_fifo_syncfifo_readable & ((~soc_basesoc_uart_tx_fifo_readable) | soc_basesoc_uart_tx_fifo_re));
assign soc_basesoc_uart_tx_fifo_level1 = (soc_basesoc_uart_tx_fifo_level0 + soc_basesoc_uart_tx_fifo_readable);
always @(*) begin
	soc_basesoc_uart_tx_fifo_wrport_adr <= 4'd0;
	if (soc_basesoc_uart_tx_fifo_replace) begin
		soc_basesoc_uart_tx_fifo_wrport_adr <= (soc_basesoc_uart_tx_fifo_produce - 1'd1);
	end else begin
		soc_basesoc_uart_tx_fifo_wrport_adr <= soc_basesoc_uart_tx_fifo_produce;
	end
end
assign soc_basesoc_uart_tx_fifo_wrport_dat_w = soc_basesoc_uart_tx_fifo_syncfifo_din;
assign soc_basesoc_uart_tx_fifo_wrport_we = (soc_basesoc_uart_tx_fifo_syncfifo_we & (soc_basesoc_uart_tx_fifo_syncfifo_writable | soc_basesoc_uart_tx_fifo_replace));
assign soc_basesoc_uart_tx_fifo_do_read = (soc_basesoc_uart_tx_fifo_syncfifo_readable & soc_basesoc_uart_tx_fifo_syncfifo_re);
assign soc_basesoc_uart_tx_fifo_rdport_adr = soc_basesoc_uart_tx_fifo_consume;
assign soc_basesoc_uart_tx_fifo_syncfifo_dout = soc_basesoc_uart_tx_fifo_rdport_dat_r;
assign soc_basesoc_uart_tx_fifo_rdport_re = soc_basesoc_uart_tx_fifo_do_read;
assign soc_basesoc_uart_tx_fifo_syncfifo_writable = (soc_basesoc_uart_tx_fifo_level0 != 5'd16);
assign soc_basesoc_uart_tx_fifo_syncfifo_readable = (soc_basesoc_uart_tx_fifo_level0 != 1'd0);
assign soc_basesoc_uart_rx_fifo_syncfifo_din = {soc_basesoc_uart_rx_fifo_fifo_in_last, soc_basesoc_uart_rx_fifo_fifo_in_first, soc_basesoc_uart_rx_fifo_fifo_in_payload_data};
assign {soc_basesoc_uart_rx_fifo_fifo_out_last, soc_basesoc_uart_rx_fifo_fifo_out_first, soc_basesoc_uart_rx_fifo_fifo_out_payload_data} = soc_basesoc_uart_rx_fifo_syncfifo_dout;
assign soc_basesoc_uart_rx_fifo_sink_ready = soc_basesoc_uart_rx_fifo_syncfifo_writable;
assign soc_basesoc_uart_rx_fifo_syncfifo_we = soc_basesoc_uart_rx_fifo_sink_valid;
assign soc_basesoc_uart_rx_fifo_fifo_in_first = soc_basesoc_uart_rx_fifo_sink_first;
assign soc_basesoc_uart_rx_fifo_fifo_in_last = soc_basesoc_uart_rx_fifo_sink_last;
assign soc_basesoc_uart_rx_fifo_fifo_in_payload_data = soc_basesoc_uart_rx_fifo_sink_payload_data;
assign soc_basesoc_uart_rx_fifo_source_valid = soc_basesoc_uart_rx_fifo_readable;
assign soc_basesoc_uart_rx_fifo_source_first = soc_basesoc_uart_rx_fifo_fifo_out_first;
assign soc_basesoc_uart_rx_fifo_source_last = soc_basesoc_uart_rx_fifo_fifo_out_last;
assign soc_basesoc_uart_rx_fifo_source_payload_data = soc_basesoc_uart_rx_fifo_fifo_out_payload_data;
assign soc_basesoc_uart_rx_fifo_re = soc_basesoc_uart_rx_fifo_source_ready;
assign soc_basesoc_uart_rx_fifo_syncfifo_re = (soc_basesoc_uart_rx_fifo_syncfifo_readable & ((~soc_basesoc_uart_rx_fifo_readable) | soc_basesoc_uart_rx_fifo_re));
assign soc_basesoc_uart_rx_fifo_level1 = (soc_basesoc_uart_rx_fifo_level0 + soc_basesoc_uart_rx_fifo_readable);
always @(*) begin
	soc_basesoc_uart_rx_fifo_wrport_adr <= 4'd0;
	if (soc_basesoc_uart_rx_fifo_replace) begin
		soc_basesoc_uart_rx_fifo_wrport_adr <= (soc_basesoc_uart_rx_fifo_produce - 1'd1);
	end else begin
		soc_basesoc_uart_rx_fifo_wrport_adr <= soc_basesoc_uart_rx_fifo_produce;
	end
end
assign soc_basesoc_uart_rx_fifo_wrport_dat_w = soc_basesoc_uart_rx_fifo_syncfifo_din;
assign soc_basesoc_uart_rx_fifo_wrport_we = (soc_basesoc_uart_rx_fifo_syncfifo_we & (soc_basesoc_uart_rx_fifo_syncfifo_writable | soc_basesoc_uart_rx_fifo_replace));
assign soc_basesoc_uart_rx_fifo_do_read = (soc_basesoc_uart_rx_fifo_syncfifo_readable & soc_basesoc_uart_rx_fifo_syncfifo_re);
assign soc_basesoc_uart_rx_fifo_rdport_adr = soc_basesoc_uart_rx_fifo_consume;
assign soc_basesoc_uart_rx_fifo_syncfifo_dout = soc_basesoc_uart_rx_fifo_rdport_dat_r;
assign soc_basesoc_uart_rx_fifo_rdport_re = soc_basesoc_uart_rx_fifo_do_read;
assign soc_basesoc_uart_rx_fifo_syncfifo_writable = (soc_basesoc_uart_rx_fifo_level0 != 5'd16);
assign soc_basesoc_uart_rx_fifo_syncfifo_readable = (soc_basesoc_uart_rx_fifo_level0 != 1'd0);
assign soc_basesoc_timer_zero_trigger = (soc_basesoc_timer_value == 1'd0);
assign soc_basesoc_timer_zero0 = soc_basesoc_timer_zero_status;
assign soc_basesoc_timer_zero1 = soc_basesoc_timer_zero_pending;
always @(*) begin
	soc_basesoc_timer_zero_clear <= 1'd0;
	if ((soc_basesoc_timer_pending_re & soc_basesoc_timer_pending_r)) begin
		soc_basesoc_timer_zero_clear <= 1'd1;
	end
end
assign soc_basesoc_timer_irq = (soc_basesoc_timer_pending_status & soc_basesoc_timer_enable_storage);
assign soc_basesoc_timer_zero_status = soc_basesoc_timer_zero_trigger;
assign soc_wait = (~soc_done);
always @(*) begin
	soc_leds <= 4'd0;
	if ((soc_mode == 1'd1)) begin
		soc_leds <= soc_storage;
	end else begin
		soc_leds <= soc_chaser;
	end
end
assign {user_led3, user_led2, user_led1, user_led0} = (soc_leds ^ 1'd0);
assign soc_done = (soc_count == 1'd0);
always @(*) begin
	soc_builder_basesoc_next_state <= 1'd0;
	soc_builder_basesoc_wishbone_dat_r <= 32'd0;
	soc_builder_basesoc_adr <= 14'd0;
	soc_builder_basesoc_we <= 1'd0;
	soc_builder_basesoc_wishbone_ack <= 1'd0;
	soc_builder_basesoc_dat_w <= 32'd0;
	soc_builder_basesoc_next_state <= soc_builder_basesoc_state;
	case (soc_builder_basesoc_state)
		1'd1: begin
			soc_builder_basesoc_wishbone_ack <= 1'd1;
			soc_builder_basesoc_wishbone_dat_r <= soc_builder_basesoc_dat_r;
			soc_builder_basesoc_next_state <= 1'd0;
		end
		default: begin
			soc_builder_basesoc_dat_w <= soc_builder_basesoc_wishbone_dat_w;
			if ((soc_builder_basesoc_wishbone_cyc & soc_builder_basesoc_wishbone_stb)) begin
				soc_builder_basesoc_adr <= soc_builder_basesoc_wishbone_adr;
				soc_builder_basesoc_we <= (soc_builder_basesoc_wishbone_we & (soc_builder_basesoc_wishbone_sel != 1'd0));
				soc_builder_basesoc_next_state <= 1'd1;
			end
		end
	endcase
end
assign soc_builder_shared_adr = soc_builder_array_muxed0;
assign soc_builder_shared_dat_w = soc_builder_array_muxed1;
assign soc_builder_shared_sel = soc_builder_array_muxed2;
assign soc_builder_shared_cyc = soc_builder_array_muxed3;
assign soc_builder_shared_stb = soc_builder_array_muxed4;
assign soc_builder_shared_we = soc_builder_array_muxed5;
assign soc_builder_shared_cti = soc_builder_array_muxed6;
assign soc_builder_shared_bte = soc_builder_array_muxed7;
assign soc_basesoc_ibus_dat_r = soc_builder_shared_dat_r;
assign soc_basesoc_dbus_dat_r = soc_builder_shared_dat_r;
assign soc_basesoc_ibus_ack = (soc_builder_shared_ack & (soc_builder_grant == 1'd0));
assign soc_basesoc_dbus_ack = (soc_builder_shared_ack & (soc_builder_grant == 1'd1));
assign soc_basesoc_ibus_err = (soc_builder_shared_err & (soc_builder_grant == 1'd0));
assign soc_basesoc_dbus_err = (soc_builder_shared_err & (soc_builder_grant == 1'd1));
assign soc_builder_request = {soc_basesoc_dbus_cyc, soc_basesoc_ibus_cyc};
always @(*) begin
	soc_builder_slave_sel <= 3'd0;
	soc_builder_slave_sel[0] <= (soc_builder_shared_adr[29:15] == 1'd0);
	soc_builder_slave_sel[1] <= (soc_builder_shared_adr[29:11] == 16'd32768);
	soc_builder_slave_sel[2] <= (soc_builder_shared_adr[29:14] == 16'd61440);
end
assign soc_basesoc_basesoc_ram_bus_adr = soc_builder_shared_adr;
assign soc_basesoc_basesoc_ram_bus_dat_w = soc_builder_shared_dat_w;
assign soc_basesoc_basesoc_ram_bus_sel = soc_builder_shared_sel;
assign soc_basesoc_basesoc_ram_bus_stb = soc_builder_shared_stb;
assign soc_basesoc_basesoc_ram_bus_we = soc_builder_shared_we;
assign soc_basesoc_basesoc_ram_bus_cti = soc_builder_shared_cti;
assign soc_basesoc_basesoc_ram_bus_bte = soc_builder_shared_bte;
assign soc_basesoc_ram_bus_ram_bus_adr = soc_builder_shared_adr;
assign soc_basesoc_ram_bus_ram_bus_dat_w = soc_builder_shared_dat_w;
assign soc_basesoc_ram_bus_ram_bus_sel = soc_builder_shared_sel;
assign soc_basesoc_ram_bus_ram_bus_stb = soc_builder_shared_stb;
assign soc_basesoc_ram_bus_ram_bus_we = soc_builder_shared_we;
assign soc_basesoc_ram_bus_ram_bus_cti = soc_builder_shared_cti;
assign soc_basesoc_ram_bus_ram_bus_bte = soc_builder_shared_bte;
assign soc_builder_basesoc_wishbone_adr = soc_builder_shared_adr;
assign soc_builder_basesoc_wishbone_dat_w = soc_builder_shared_dat_w;
assign soc_builder_basesoc_wishbone_sel = soc_builder_shared_sel;
assign soc_builder_basesoc_wishbone_stb = soc_builder_shared_stb;
assign soc_builder_basesoc_wishbone_we = soc_builder_shared_we;
assign soc_builder_basesoc_wishbone_cti = soc_builder_shared_cti;
assign soc_builder_basesoc_wishbone_bte = soc_builder_shared_bte;
assign soc_basesoc_basesoc_ram_bus_cyc = (soc_builder_shared_cyc & soc_builder_slave_sel[0]);
assign soc_basesoc_ram_bus_ram_bus_cyc = (soc_builder_shared_cyc & soc_builder_slave_sel[1]);
assign soc_builder_basesoc_wishbone_cyc = (soc_builder_shared_cyc & soc_builder_slave_sel[2]);
assign soc_builder_shared_err = ((soc_basesoc_basesoc_ram_bus_err | soc_basesoc_ram_bus_ram_bus_err) | soc_builder_basesoc_wishbone_err);
assign soc_builder_wait = ((soc_builder_shared_stb & soc_builder_shared_cyc) & (~soc_builder_shared_ack));
always @(*) begin
	soc_builder_shared_dat_r <= 32'd0;
	soc_builder_error <= 1'd0;
	soc_builder_shared_ack <= 1'd0;
	soc_builder_shared_ack <= ((soc_basesoc_basesoc_ram_bus_ack | soc_basesoc_ram_bus_ram_bus_ack) | soc_builder_basesoc_wishbone_ack);
	soc_builder_shared_dat_r <= ((({32{soc_builder_slave_sel_r[0]}} & soc_basesoc_basesoc_ram_bus_dat_r) | ({32{soc_builder_slave_sel_r[1]}} & soc_basesoc_ram_bus_ram_bus_dat_r)) | ({32{soc_builder_slave_sel_r[2]}} & soc_builder_basesoc_wishbone_dat_r));
	if (soc_builder_done) begin
		soc_builder_shared_dat_r <= 32'd4294967295;
		soc_builder_shared_ack <= 1'd1;
		soc_builder_error <= 1'd1;
	end
end
assign soc_builder_done = (soc_builder_count == 1'd0);
assign soc_builder_csr_bankarray_csrbank0_sel = (soc_builder_csr_bankarray_interface0_bank_bus_adr[13:9] == 1'd0);
assign soc_builder_csr_bankarray_csrbank0_reset0_r = soc_builder_csr_bankarray_interface0_bank_bus_dat_w[1:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank0_reset0_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank0_reset0_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank0_sel & (soc_builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd0))) begin
		soc_builder_csr_bankarray_csrbank0_reset0_re <= soc_builder_csr_bankarray_interface0_bank_bus_we;
		soc_builder_csr_bankarray_csrbank0_reset0_we <= (~soc_builder_csr_bankarray_interface0_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank0_scratch0_r = soc_builder_csr_bankarray_interface0_bank_bus_dat_w[31:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank0_scratch0_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank0_scratch0_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank0_sel & (soc_builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd1))) begin
		soc_builder_csr_bankarray_csrbank0_scratch0_re <= soc_builder_csr_bankarray_interface0_bank_bus_we;
		soc_builder_csr_bankarray_csrbank0_scratch0_we <= (~soc_builder_csr_bankarray_interface0_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank0_bus_errors_r = soc_builder_csr_bankarray_interface0_bank_bus_dat_w[31:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank0_bus_errors_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank0_bus_errors_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank0_sel & (soc_builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 2'd2))) begin
		soc_builder_csr_bankarray_csrbank0_bus_errors_re <= soc_builder_csr_bankarray_interface0_bank_bus_we;
		soc_builder_csr_bankarray_csrbank0_bus_errors_we <= (~soc_builder_csr_bankarray_interface0_bank_bus_we);
	end
end
always @(*) begin
	soc_basesoc_soc_rst <= 1'd0;
	if (soc_basesoc_reset_re) begin
		soc_basesoc_soc_rst <= soc_basesoc_reset_storage[0];
	end
end
assign soc_basesoc_cpu_rst = soc_basesoc_reset_storage[1];
assign soc_builder_csr_bankarray_csrbank0_reset0_w = soc_basesoc_reset_storage[1:0];
assign soc_builder_csr_bankarray_csrbank0_scratch0_w = soc_basesoc_scratch_storage[31:0];
assign soc_builder_csr_bankarray_csrbank0_bus_errors_w = soc_basesoc_bus_errors_status[31:0];
assign soc_basesoc_bus_errors_we = soc_builder_csr_bankarray_csrbank0_bus_errors_we;
assign soc_builder_csr_bankarray_sel = (soc_builder_csr_bankarray_sram_bus_adr[13:9] == 1'd1);
always @(*) begin
	soc_builder_csr_bankarray_sram_bus_dat_r <= 32'd0;
	if (soc_builder_csr_bankarray_sel_r) begin
		soc_builder_csr_bankarray_sram_bus_dat_r <= soc_builder_csr_bankarray_dat_r;
	end
end
assign soc_builder_csr_bankarray_adr = soc_builder_csr_bankarray_sram_bus_adr[5:0];
assign soc_builder_csr_bankarray_csrbank1_sel = (soc_builder_csr_bankarray_interface1_bank_bus_adr[13:9] == 2'd2);
assign soc_builder_csr_bankarray_csrbank1_out0_r = soc_builder_csr_bankarray_interface1_bank_bus_dat_w[3:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank1_out0_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank1_out0_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank1_sel & (soc_builder_csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd0))) begin
		soc_builder_csr_bankarray_csrbank1_out0_re <= soc_builder_csr_bankarray_interface1_bank_bus_we;
		soc_builder_csr_bankarray_csrbank1_out0_we <= (~soc_builder_csr_bankarray_interface1_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank1_out0_w = soc_storage[3:0];
assign soc_builder_csr_bankarray_csrbank2_sel = (soc_builder_csr_bankarray_interface2_bank_bus_adr[13:9] == 2'd3);
assign soc_builder_csr_bankarray_csrbank2_load0_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[31:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_load0_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_load0_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd0))) begin
		soc_builder_csr_bankarray_csrbank2_load0_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_load0_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_reload0_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[31:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_reload0_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_reload0_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd1))) begin
		soc_builder_csr_bankarray_csrbank2_reload0_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_reload0_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_en0_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_en0_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_en0_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd2))) begin
		soc_builder_csr_bankarray_csrbank2_en0_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_en0_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_update_value0_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_update_value0_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_update_value0_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd3))) begin
		soc_builder_csr_bankarray_csrbank2_update_value0_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_update_value0_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_value_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[31:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_value_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_value_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd4))) begin
		soc_builder_csr_bankarray_csrbank2_value_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_value_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_ev_status_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_ev_status_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_ev_status_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd5))) begin
		soc_builder_csr_bankarray_csrbank2_ev_status_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_ev_status_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_ev_pending_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_ev_pending_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_ev_pending_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd6))) begin
		soc_builder_csr_bankarray_csrbank2_ev_pending_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_ev_pending_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_ev_enable0_r = soc_builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank2_ev_enable0_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank2_ev_enable0_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank2_sel & (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd7))) begin
		soc_builder_csr_bankarray_csrbank2_ev_enable0_re <= soc_builder_csr_bankarray_interface2_bank_bus_we;
		soc_builder_csr_bankarray_csrbank2_ev_enable0_we <= (~soc_builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank2_load0_w = soc_basesoc_timer_load_storage[31:0];
assign soc_builder_csr_bankarray_csrbank2_reload0_w = soc_basesoc_timer_reload_storage[31:0];
assign soc_builder_csr_bankarray_csrbank2_en0_w = soc_basesoc_timer_en_storage;
assign soc_builder_csr_bankarray_csrbank2_update_value0_w = soc_basesoc_timer_update_value_storage;
assign soc_builder_csr_bankarray_csrbank2_value_w = soc_basesoc_timer_value_status[31:0];
assign soc_basesoc_timer_value_we = soc_builder_csr_bankarray_csrbank2_value_we;
assign soc_basesoc_timer_status_status = soc_basesoc_timer_zero0;
assign soc_builder_csr_bankarray_csrbank2_ev_status_w = soc_basesoc_timer_status_status;
assign soc_basesoc_timer_status_we = soc_builder_csr_bankarray_csrbank2_ev_status_we;
assign soc_basesoc_timer_pending_status = soc_basesoc_timer_zero1;
assign soc_builder_csr_bankarray_csrbank2_ev_pending_w = soc_basesoc_timer_pending_status;
assign soc_basesoc_timer_pending_we = soc_builder_csr_bankarray_csrbank2_ev_pending_we;
assign soc_basesoc_timer_zero2 = soc_basesoc_timer_enable_storage;
assign soc_builder_csr_bankarray_csrbank2_ev_enable0_w = soc_basesoc_timer_enable_storage;
assign soc_builder_csr_bankarray_csrbank3_sel = (soc_builder_csr_bankarray_interface3_bank_bus_adr[13:9] == 3'd4);
assign soc_basesoc_uart_rxtx_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[7:0];
always @(*) begin
	soc_basesoc_uart_rxtx_re <= 1'd0;
	soc_basesoc_uart_rxtx_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 1'd0))) begin
		soc_basesoc_uart_rxtx_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_basesoc_uart_rxtx_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_txfull_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_txfull_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_txfull_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 1'd1))) begin
		soc_builder_csr_bankarray_csrbank3_txfull_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_txfull_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_rxempty_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_rxempty_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_rxempty_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 2'd2))) begin
		soc_builder_csr_bankarray_csrbank3_rxempty_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_rxempty_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_ev_status_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_ev_status_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_ev_status_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 2'd3))) begin
		soc_builder_csr_bankarray_csrbank3_ev_status_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_ev_status_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_ev_pending_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_ev_pending_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_ev_pending_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd4))) begin
		soc_builder_csr_bankarray_csrbank3_ev_pending_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_ev_pending_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_ev_enable0_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_ev_enable0_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_ev_enable0_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd5))) begin
		soc_builder_csr_bankarray_csrbank3_ev_enable0_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_ev_enable0_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_txempty_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_txempty_re <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_txempty_we <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd6))) begin
		soc_builder_csr_bankarray_csrbank3_txempty_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_txempty_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_rxfull_r = soc_builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	soc_builder_csr_bankarray_csrbank3_rxfull_we <= 1'd0;
	soc_builder_csr_bankarray_csrbank3_rxfull_re <= 1'd0;
	if ((soc_builder_csr_bankarray_csrbank3_sel & (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd7))) begin
		soc_builder_csr_bankarray_csrbank3_rxfull_re <= soc_builder_csr_bankarray_interface3_bank_bus_we;
		soc_builder_csr_bankarray_csrbank3_rxfull_we <= (~soc_builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign soc_builder_csr_bankarray_csrbank3_txfull_w = soc_basesoc_uart_txfull_status;
assign soc_basesoc_uart_txfull_we = soc_builder_csr_bankarray_csrbank3_txfull_we;
assign soc_builder_csr_bankarray_csrbank3_rxempty_w = soc_basesoc_uart_rxempty_status;
assign soc_basesoc_uart_rxempty_we = soc_builder_csr_bankarray_csrbank3_rxempty_we;
always @(*) begin
	soc_basesoc_uart_status_status <= 2'd0;
	soc_basesoc_uart_status_status[0] <= soc_basesoc_uart_tx0;
	soc_basesoc_uart_status_status[1] <= soc_basesoc_uart_rx0;
end
assign soc_builder_csr_bankarray_csrbank3_ev_status_w = soc_basesoc_uart_status_status[1:0];
assign soc_basesoc_uart_status_we = soc_builder_csr_bankarray_csrbank3_ev_status_we;
always @(*) begin
	soc_basesoc_uart_pending_status <= 2'd0;
	soc_basesoc_uart_pending_status[0] <= soc_basesoc_uart_tx1;
	soc_basesoc_uart_pending_status[1] <= soc_basesoc_uart_rx1;
end
assign soc_builder_csr_bankarray_csrbank3_ev_pending_w = soc_basesoc_uart_pending_status[1:0];
assign soc_basesoc_uart_pending_we = soc_builder_csr_bankarray_csrbank3_ev_pending_we;
assign soc_basesoc_uart_tx2 = soc_basesoc_uart_enable_storage[0];
assign soc_basesoc_uart_rx2 = soc_basesoc_uart_enable_storage[1];
assign soc_builder_csr_bankarray_csrbank3_ev_enable0_w = soc_basesoc_uart_enable_storage[1:0];
assign soc_builder_csr_bankarray_csrbank3_txempty_w = soc_basesoc_uart_txempty_status;
assign soc_basesoc_uart_txempty_we = soc_builder_csr_bankarray_csrbank3_txempty_we;
assign soc_builder_csr_bankarray_csrbank3_rxfull_w = soc_basesoc_uart_rxfull_status;
assign soc_basesoc_uart_rxfull_we = soc_builder_csr_bankarray_csrbank3_rxfull_we;
assign soc_builder_csr_interconnect_adr = soc_builder_basesoc_adr;
assign soc_builder_csr_interconnect_we = soc_builder_basesoc_we;
assign soc_builder_csr_interconnect_dat_w = soc_builder_basesoc_dat_w;
assign soc_builder_basesoc_dat_r = soc_builder_csr_interconnect_dat_r;
assign soc_builder_csr_bankarray_interface0_bank_bus_adr = soc_builder_csr_interconnect_adr;
assign soc_builder_csr_bankarray_interface1_bank_bus_adr = soc_builder_csr_interconnect_adr;
assign soc_builder_csr_bankarray_interface2_bank_bus_adr = soc_builder_csr_interconnect_adr;
assign soc_builder_csr_bankarray_interface3_bank_bus_adr = soc_builder_csr_interconnect_adr;
assign soc_builder_csr_bankarray_sram_bus_adr = soc_builder_csr_interconnect_adr;
assign soc_builder_csr_bankarray_interface0_bank_bus_we = soc_builder_csr_interconnect_we;
assign soc_builder_csr_bankarray_interface1_bank_bus_we = soc_builder_csr_interconnect_we;
assign soc_builder_csr_bankarray_interface2_bank_bus_we = soc_builder_csr_interconnect_we;
assign soc_builder_csr_bankarray_interface3_bank_bus_we = soc_builder_csr_interconnect_we;
assign soc_builder_csr_bankarray_sram_bus_we = soc_builder_csr_interconnect_we;
assign soc_builder_csr_bankarray_interface0_bank_bus_dat_w = soc_builder_csr_interconnect_dat_w;
assign soc_builder_csr_bankarray_interface1_bank_bus_dat_w = soc_builder_csr_interconnect_dat_w;
assign soc_builder_csr_bankarray_interface2_bank_bus_dat_w = soc_builder_csr_interconnect_dat_w;
assign soc_builder_csr_bankarray_interface3_bank_bus_dat_w = soc_builder_csr_interconnect_dat_w;
assign soc_builder_csr_bankarray_sram_bus_dat_w = soc_builder_csr_interconnect_dat_w;
assign soc_builder_csr_interconnect_dat_r = ((((soc_builder_csr_bankarray_interface0_bank_bus_dat_r | soc_builder_csr_bankarray_interface1_bank_bus_dat_r) | soc_builder_csr_bankarray_interface2_bank_bus_dat_r) | soc_builder_csr_bankarray_interface3_bank_bus_dat_r) | soc_builder_csr_bankarray_sram_bus_dat_r);
always @(*) begin
	soc_builder_array_muxed0 <= 30'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed0 <= soc_basesoc_ibus_adr;
		end
		default: begin
			soc_builder_array_muxed0 <= soc_basesoc_dbus_adr;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed1 <= 32'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed1 <= soc_basesoc_ibus_dat_w;
		end
		default: begin
			soc_builder_array_muxed1 <= soc_basesoc_dbus_dat_w;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed2 <= 4'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed2 <= soc_basesoc_ibus_sel;
		end
		default: begin
			soc_builder_array_muxed2 <= soc_basesoc_dbus_sel;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed3 <= 1'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed3 <= soc_basesoc_ibus_cyc;
		end
		default: begin
			soc_builder_array_muxed3 <= soc_basesoc_dbus_cyc;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed4 <= 1'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed4 <= soc_basesoc_ibus_stb;
		end
		default: begin
			soc_builder_array_muxed4 <= soc_basesoc_dbus_stb;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed5 <= 1'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed5 <= soc_basesoc_ibus_we;
		end
		default: begin
			soc_builder_array_muxed5 <= soc_basesoc_dbus_we;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed6 <= 3'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed6 <= soc_basesoc_ibus_cti;
		end
		default: begin
			soc_builder_array_muxed6 <= soc_basesoc_dbus_cti;
		end
	endcase
end
always @(*) begin
	soc_builder_array_muxed7 <= 2'd0;
	case (soc_builder_grant)
		1'd0: begin
			soc_builder_array_muxed7 <= soc_basesoc_ibus_bte;
		end
		default: begin
			soc_builder_array_muxed7 <= soc_basesoc_dbus_bte;
		end
	endcase
end
assign soc_builder_xilinxasyncresetsynchronizerimpl = (~soc_crg_locked);
assign soc_basesoc_rx_rx = soc_builder_regs1;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge sys_clk) begin
	if ((soc_basesoc_bus_errors != 32'd4294967295)) begin
		if (soc_basesoc_bus_error) begin
			soc_basesoc_bus_errors <= (soc_basesoc_bus_errors + 1'd1);
		end
	end
	soc_basesoc_basesoc_ram_bus_ack <= 1'd0;
	if (((soc_basesoc_basesoc_ram_bus_cyc & soc_basesoc_basesoc_ram_bus_stb) & ((~soc_basesoc_basesoc_ram_bus_ack) | soc_basesoc_basesoc_adr_burst))) begin
		soc_basesoc_basesoc_ram_bus_ack <= 1'd1;
	end
	soc_basesoc_ram_bus_ram_bus_ack <= 1'd0;
	if (((soc_basesoc_ram_bus_ram_bus_cyc & soc_basesoc_ram_bus_ram_bus_stb) & ((~soc_basesoc_ram_bus_ram_bus_ack) | soc_basesoc_ram_adr_burst))) begin
		soc_basesoc_ram_bus_ram_bus_ack <= 1'd1;
	end
	{soc_basesoc_tx_tick, soc_basesoc_tx_phase} <= 27'd79164837;
	if (soc_basesoc_tx_enable) begin
		{soc_basesoc_tx_tick, soc_basesoc_tx_phase} <= (soc_basesoc_tx_phase + 27'd79164837);
	end
	soc_builder_basesoc_rs232phytx_state <= soc_builder_basesoc_rs232phytx_next_state;
	if (soc_basesoc_tx_count_rs232phytx_next_value_ce0) begin
		soc_basesoc_tx_count <= soc_basesoc_tx_count_rs232phytx_next_value0;
	end
	if (soc_basesoc_usb_uart_tx_rs232phytx_next_value_ce1) begin
		usb_uart_tx <= soc_basesoc_usb_uart_tx_rs232phytx_next_value1;
	end
	if (soc_basesoc_tx_data_rs232phytx_next_value_ce2) begin
		soc_basesoc_tx_data <= soc_basesoc_tx_data_rs232phytx_next_value2;
	end
	soc_basesoc_rx_rx_d <= soc_basesoc_rx_rx;
	{soc_basesoc_rx_tick, soc_basesoc_rx_phase} <= 32'd2147483648;
	if (soc_basesoc_rx_enable) begin
		{soc_basesoc_rx_tick, soc_basesoc_rx_phase} <= (soc_basesoc_rx_phase + 27'd79164837);
	end
	soc_builder_basesoc_rs232phyrx_state <= soc_builder_basesoc_rs232phyrx_next_state;
	if (soc_basesoc_rx_count_rs232phyrx_next_value_ce0) begin
		soc_basesoc_rx_count <= soc_basesoc_rx_count_rs232phyrx_next_value0;
	end
	if (soc_basesoc_rx_data_rs232phyrx_next_value_ce1) begin
		soc_basesoc_rx_data <= soc_basesoc_rx_data_rs232phyrx_next_value1;
	end
	if (soc_basesoc_uart_tx_clear) begin
		soc_basesoc_uart_tx_pending <= 1'd0;
	end
	soc_basesoc_uart_tx_trigger_d <= soc_basesoc_uart_tx_trigger;
	if ((soc_basesoc_uart_tx_trigger & (~soc_basesoc_uart_tx_trigger_d))) begin
		soc_basesoc_uart_tx_pending <= 1'd1;
	end
	if (soc_basesoc_uart_rx_clear) begin
		soc_basesoc_uart_rx_pending <= 1'd0;
	end
	soc_basesoc_uart_rx_trigger_d <= soc_basesoc_uart_rx_trigger;
	if ((soc_basesoc_uart_rx_trigger & (~soc_basesoc_uart_rx_trigger_d))) begin
		soc_basesoc_uart_rx_pending <= 1'd1;
	end
	if (soc_basesoc_uart_tx_fifo_syncfifo_re) begin
		soc_basesoc_uart_tx_fifo_readable <= 1'd1;
	end else begin
		if (soc_basesoc_uart_tx_fifo_re) begin
			soc_basesoc_uart_tx_fifo_readable <= 1'd0;
		end
	end
	if (((soc_basesoc_uart_tx_fifo_syncfifo_we & soc_basesoc_uart_tx_fifo_syncfifo_writable) & (~soc_basesoc_uart_tx_fifo_replace))) begin
		soc_basesoc_uart_tx_fifo_produce <= (soc_basesoc_uart_tx_fifo_produce + 1'd1);
	end
	if (soc_basesoc_uart_tx_fifo_do_read) begin
		soc_basesoc_uart_tx_fifo_consume <= (soc_basesoc_uart_tx_fifo_consume + 1'd1);
	end
	if (((soc_basesoc_uart_tx_fifo_syncfifo_we & soc_basesoc_uart_tx_fifo_syncfifo_writable) & (~soc_basesoc_uart_tx_fifo_replace))) begin
		if ((~soc_basesoc_uart_tx_fifo_do_read)) begin
			soc_basesoc_uart_tx_fifo_level0 <= (soc_basesoc_uart_tx_fifo_level0 + 1'd1);
		end
	end else begin
		if (soc_basesoc_uart_tx_fifo_do_read) begin
			soc_basesoc_uart_tx_fifo_level0 <= (soc_basesoc_uart_tx_fifo_level0 - 1'd1);
		end
	end
	if (soc_basesoc_uart_rx_fifo_syncfifo_re) begin
		soc_basesoc_uart_rx_fifo_readable <= 1'd1;
	end else begin
		if (soc_basesoc_uart_rx_fifo_re) begin
			soc_basesoc_uart_rx_fifo_readable <= 1'd0;
		end
	end
	if (((soc_basesoc_uart_rx_fifo_syncfifo_we & soc_basesoc_uart_rx_fifo_syncfifo_writable) & (~soc_basesoc_uart_rx_fifo_replace))) begin
		soc_basesoc_uart_rx_fifo_produce <= (soc_basesoc_uart_rx_fifo_produce + 1'd1);
	end
	if (soc_basesoc_uart_rx_fifo_do_read) begin
		soc_basesoc_uart_rx_fifo_consume <= (soc_basesoc_uart_rx_fifo_consume + 1'd1);
	end
	if (((soc_basesoc_uart_rx_fifo_syncfifo_we & soc_basesoc_uart_rx_fifo_syncfifo_writable) & (~soc_basesoc_uart_rx_fifo_replace))) begin
		if ((~soc_basesoc_uart_rx_fifo_do_read)) begin
			soc_basesoc_uart_rx_fifo_level0 <= (soc_basesoc_uart_rx_fifo_level0 + 1'd1);
		end
	end else begin
		if (soc_basesoc_uart_rx_fifo_do_read) begin
			soc_basesoc_uart_rx_fifo_level0 <= (soc_basesoc_uart_rx_fifo_level0 - 1'd1);
		end
	end
	if (soc_basesoc_timer_en_storage) begin
		if ((soc_basesoc_timer_value == 1'd0)) begin
			soc_basesoc_timer_value <= soc_basesoc_timer_reload_storage;
		end else begin
			soc_basesoc_timer_value <= (soc_basesoc_timer_value - 1'd1);
		end
	end else begin
		soc_basesoc_timer_value <= soc_basesoc_timer_load_storage;
	end
	if (soc_basesoc_timer_update_value_re) begin
		soc_basesoc_timer_value_status <= soc_basesoc_timer_value;
	end
	if (soc_basesoc_timer_zero_clear) begin
		soc_basesoc_timer_zero_pending <= 1'd0;
	end
	soc_basesoc_timer_zero_trigger_d <= soc_basesoc_timer_zero_trigger;
	if ((soc_basesoc_timer_zero_trigger & (~soc_basesoc_timer_zero_trigger_d))) begin
		soc_basesoc_timer_zero_pending <= 1'd1;
	end
	if (soc_done) begin
		soc_chaser <= {soc_chaser, (~soc_chaser[3])};
	end
	if (soc_re) begin
		soc_mode <= 1'd1;
	end
	if (soc_wait) begin
		if ((~soc_done)) begin
			soc_count <= (soc_count - 1'd1);
		end
	end else begin
		soc_count <= 24'd12500000;
	end
	soc_builder_basesoc_state <= soc_builder_basesoc_next_state;
	case (soc_builder_grant)
		1'd0: begin
			if ((~soc_builder_request[0])) begin
				if (soc_builder_request[1]) begin
					soc_builder_grant <= 1'd1;
				end
			end
		end
		1'd1: begin
			if ((~soc_builder_request[1])) begin
				if (soc_builder_request[0]) begin
					soc_builder_grant <= 1'd0;
				end
			end
		end
	endcase
	soc_builder_slave_sel_r <= soc_builder_slave_sel;
	if (soc_builder_wait) begin
		if ((~soc_builder_done)) begin
			soc_builder_count <= (soc_builder_count - 1'd1);
		end
	end else begin
		soc_builder_count <= 20'd1000000;
	end
	soc_builder_csr_bankarray_interface0_bank_bus_dat_r <= 1'd0;
	if (soc_builder_csr_bankarray_csrbank0_sel) begin
		case (soc_builder_csr_bankarray_interface0_bank_bus_adr[8:0])
			1'd0: begin
				soc_builder_csr_bankarray_interface0_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank0_reset0_w;
			end
			1'd1: begin
				soc_builder_csr_bankarray_interface0_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank0_scratch0_w;
			end
			2'd2: begin
				soc_builder_csr_bankarray_interface0_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank0_bus_errors_w;
			end
		endcase
	end
	if (soc_builder_csr_bankarray_csrbank0_reset0_re) begin
		soc_basesoc_reset_storage[1:0] <= soc_builder_csr_bankarray_csrbank0_reset0_r;
	end
	soc_basesoc_reset_re <= soc_builder_csr_bankarray_csrbank0_reset0_re;
	if (soc_builder_csr_bankarray_csrbank0_scratch0_re) begin
		soc_basesoc_scratch_storage[31:0] <= soc_builder_csr_bankarray_csrbank0_scratch0_r;
	end
	soc_basesoc_scratch_re <= soc_builder_csr_bankarray_csrbank0_scratch0_re;
	soc_basesoc_bus_errors_re <= soc_builder_csr_bankarray_csrbank0_bus_errors_re;
	soc_builder_csr_bankarray_sel_r <= soc_builder_csr_bankarray_sel;
	soc_builder_csr_bankarray_interface1_bank_bus_dat_r <= 1'd0;
	if (soc_builder_csr_bankarray_csrbank1_sel) begin
		case (soc_builder_csr_bankarray_interface1_bank_bus_adr[8:0])
			1'd0: begin
				soc_builder_csr_bankarray_interface1_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank1_out0_w;
			end
		endcase
	end
	if (soc_builder_csr_bankarray_csrbank1_out0_re) begin
		soc_storage[3:0] <= soc_builder_csr_bankarray_csrbank1_out0_r;
	end
	soc_re <= soc_builder_csr_bankarray_csrbank1_out0_re;
	soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= 1'd0;
	if (soc_builder_csr_bankarray_csrbank2_sel) begin
		case (soc_builder_csr_bankarray_interface2_bank_bus_adr[8:0])
			1'd0: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_load0_w;
			end
			1'd1: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_reload0_w;
			end
			2'd2: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_en0_w;
			end
			2'd3: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_update_value0_w;
			end
			3'd4: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_value_w;
			end
			3'd5: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_ev_status_w;
			end
			3'd6: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_ev_pending_w;
			end
			3'd7: begin
				soc_builder_csr_bankarray_interface2_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank2_ev_enable0_w;
			end
		endcase
	end
	if (soc_builder_csr_bankarray_csrbank2_load0_re) begin
		soc_basesoc_timer_load_storage[31:0] <= soc_builder_csr_bankarray_csrbank2_load0_r;
	end
	soc_basesoc_timer_load_re <= soc_builder_csr_bankarray_csrbank2_load0_re;
	if (soc_builder_csr_bankarray_csrbank2_reload0_re) begin
		soc_basesoc_timer_reload_storage[31:0] <= soc_builder_csr_bankarray_csrbank2_reload0_r;
	end
	soc_basesoc_timer_reload_re <= soc_builder_csr_bankarray_csrbank2_reload0_re;
	if (soc_builder_csr_bankarray_csrbank2_en0_re) begin
		soc_basesoc_timer_en_storage <= soc_builder_csr_bankarray_csrbank2_en0_r;
	end
	soc_basesoc_timer_en_re <= soc_builder_csr_bankarray_csrbank2_en0_re;
	if (soc_builder_csr_bankarray_csrbank2_update_value0_re) begin
		soc_basesoc_timer_update_value_storage <= soc_builder_csr_bankarray_csrbank2_update_value0_r;
	end
	soc_basesoc_timer_update_value_re <= soc_builder_csr_bankarray_csrbank2_update_value0_re;
	soc_basesoc_timer_value_re <= soc_builder_csr_bankarray_csrbank2_value_re;
	soc_basesoc_timer_status_re <= soc_builder_csr_bankarray_csrbank2_ev_status_re;
	if (soc_builder_csr_bankarray_csrbank2_ev_pending_re) begin
		soc_basesoc_timer_pending_r <= soc_builder_csr_bankarray_csrbank2_ev_pending_r;
	end
	soc_basesoc_timer_pending_re <= soc_builder_csr_bankarray_csrbank2_ev_pending_re;
	if (soc_builder_csr_bankarray_csrbank2_ev_enable0_re) begin
		soc_basesoc_timer_enable_storage <= soc_builder_csr_bankarray_csrbank2_ev_enable0_r;
	end
	soc_basesoc_timer_enable_re <= soc_builder_csr_bankarray_csrbank2_ev_enable0_re;
	soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= 1'd0;
	if (soc_builder_csr_bankarray_csrbank3_sel) begin
		case (soc_builder_csr_bankarray_interface3_bank_bus_adr[8:0])
			1'd0: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_basesoc_uart_rxtx_w;
			end
			1'd1: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_txfull_w;
			end
			2'd2: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_rxempty_w;
			end
			2'd3: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_ev_status_w;
			end
			3'd4: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_ev_pending_w;
			end
			3'd5: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_ev_enable0_w;
			end
			3'd6: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_txempty_w;
			end
			3'd7: begin
				soc_builder_csr_bankarray_interface3_bank_bus_dat_r <= soc_builder_csr_bankarray_csrbank3_rxfull_w;
			end
		endcase
	end
	soc_basesoc_uart_txfull_re <= soc_builder_csr_bankarray_csrbank3_txfull_re;
	soc_basesoc_uart_rxempty_re <= soc_builder_csr_bankarray_csrbank3_rxempty_re;
	soc_basesoc_uart_status_re <= soc_builder_csr_bankarray_csrbank3_ev_status_re;
	if (soc_builder_csr_bankarray_csrbank3_ev_pending_re) begin
		soc_basesoc_uart_pending_r[1:0] <= soc_builder_csr_bankarray_csrbank3_ev_pending_r;
	end
	soc_basesoc_uart_pending_re <= soc_builder_csr_bankarray_csrbank3_ev_pending_re;
	if (soc_builder_csr_bankarray_csrbank3_ev_enable0_re) begin
		soc_basesoc_uart_enable_storage[1:0] <= soc_builder_csr_bankarray_csrbank3_ev_enable0_r;
	end
	soc_basesoc_uart_enable_re <= soc_builder_csr_bankarray_csrbank3_ev_enable0_re;
	soc_basesoc_uart_txempty_re <= soc_builder_csr_bankarray_csrbank3_txempty_re;
	soc_basesoc_uart_rxfull_re <= soc_builder_csr_bankarray_csrbank3_rxfull_re;
	if (sys_rst) begin
		soc_basesoc_reset_storage <= 2'd0;
		soc_basesoc_reset_re <= 1'd0;
		soc_basesoc_scratch_storage <= 32'd305419896;
		soc_basesoc_scratch_re <= 1'd0;
		soc_basesoc_bus_errors_re <= 1'd0;
		soc_basesoc_bus_errors <= 32'd0;
		soc_basesoc_basesoc_ram_bus_ack <= 1'd0;
		soc_basesoc_ram_bus_ram_bus_ack <= 1'd0;
		usb_uart_tx <= 1'd1;
		soc_basesoc_tx_tick <= 1'd0;
		soc_basesoc_rx_tick <= 1'd0;
		soc_basesoc_rx_rx_d <= 1'd0;
		soc_basesoc_uart_txfull_re <= 1'd0;
		soc_basesoc_uart_rxempty_re <= 1'd0;
		soc_basesoc_uart_tx_pending <= 1'd0;
		soc_basesoc_uart_tx_trigger_d <= 1'd0;
		soc_basesoc_uart_rx_pending <= 1'd0;
		soc_basesoc_uart_rx_trigger_d <= 1'd0;
		soc_basesoc_uart_status_re <= 1'd0;
		soc_basesoc_uart_pending_re <= 1'd0;
		soc_basesoc_uart_pending_r <= 2'd0;
		soc_basesoc_uart_enable_storage <= 2'd0;
		soc_basesoc_uart_enable_re <= 1'd0;
		soc_basesoc_uart_txempty_re <= 1'd0;
		soc_basesoc_uart_rxfull_re <= 1'd0;
		soc_basesoc_uart_tx_fifo_readable <= 1'd0;
		soc_basesoc_uart_tx_fifo_level0 <= 5'd0;
		soc_basesoc_uart_tx_fifo_produce <= 4'd0;
		soc_basesoc_uart_tx_fifo_consume <= 4'd0;
		soc_basesoc_uart_rx_fifo_readable <= 1'd0;
		soc_basesoc_uart_rx_fifo_level0 <= 5'd0;
		soc_basesoc_uart_rx_fifo_produce <= 4'd0;
		soc_basesoc_uart_rx_fifo_consume <= 4'd0;
		soc_basesoc_timer_load_storage <= 32'd0;
		soc_basesoc_timer_load_re <= 1'd0;
		soc_basesoc_timer_reload_storage <= 32'd0;
		soc_basesoc_timer_reload_re <= 1'd0;
		soc_basesoc_timer_en_storage <= 1'd0;
		soc_basesoc_timer_en_re <= 1'd0;
		soc_basesoc_timer_update_value_storage <= 1'd0;
		soc_basesoc_timer_update_value_re <= 1'd0;
		soc_basesoc_timer_value_status <= 32'd0;
		soc_basesoc_timer_value_re <= 1'd0;
		soc_basesoc_timer_zero_pending <= 1'd0;
		soc_basesoc_timer_zero_trigger_d <= 1'd0;
		soc_basesoc_timer_status_re <= 1'd0;
		soc_basesoc_timer_pending_re <= 1'd0;
		soc_basesoc_timer_pending_r <= 1'd0;
		soc_basesoc_timer_enable_storage <= 1'd0;
		soc_basesoc_timer_enable_re <= 1'd0;
		soc_basesoc_timer_value <= 32'd0;
		soc_storage <= 4'd0;
		soc_re <= 1'd0;
		soc_chaser <= 4'd0;
		soc_mode <= 1'd0;
		soc_count <= 24'd12500000;
		soc_builder_grant <= 1'd0;
		soc_builder_slave_sel_r <= 3'd0;
		soc_builder_count <= 20'd1000000;
		soc_builder_csr_bankarray_sel_r <= 1'd0;
		soc_builder_basesoc_rs232phytx_state <= 1'd0;
		soc_builder_basesoc_rs232phyrx_state <= 1'd0;
		soc_builder_basesoc_state <= 1'd0;
	end
	soc_builder_regs0 <= usb_uart_rx;
	soc_builder_regs1 <= soc_builder_regs0;
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

BUFG BUFG(
	.I(soc_crg_clkout),
	.O(soc_crg_clkout_buf)
);

//------------------------------------------------------------------------------
// Memory rom: 32768-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [31:0] rom[0:32767];
initial begin
	$readmemh("tul_pynq_z2_rom.init", rom);
end
reg [31:0] rom_dat0;
always @(posedge sys_clk) begin
	rom_dat0 <= rom[soc_basesoc_basesoc_adr];
end
assign soc_basesoc_basesoc_dat_r = rom_dat0;


//------------------------------------------------------------------------------
// Memory sram: 2048-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8 
reg [31:0] sram[0:2047];
initial begin
	$readmemh("tul_pynq_z2_sram.init", sram);
end
reg [10:0] sram_adr0;
always @(posedge sys_clk) begin
	if (soc_basesoc_ram_we[0])
		sram[soc_basesoc_ram_adr][7:0] <= soc_basesoc_ram_dat_w[7:0];
	if (soc_basesoc_ram_we[1])
		sram[soc_basesoc_ram_adr][15:8] <= soc_basesoc_ram_dat_w[15:8];
	if (soc_basesoc_ram_we[2])
		sram[soc_basesoc_ram_adr][23:16] <= soc_basesoc_ram_dat_w[23:16];
	if (soc_basesoc_ram_we[3])
		sram[soc_basesoc_ram_adr][31:24] <= soc_basesoc_ram_dat_w[31:24];
	sram_adr0 <= soc_basesoc_ram_adr;
end
assign soc_basesoc_ram_dat_r = sram[sram_adr0];


//------------------------------------------------------------------------------
// Memory mem: 41-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] mem[0:40];
initial begin
	$readmemh("tul_pynq_z2_mem.init", mem);
end
reg [5:0] mem_adr0;
always @(posedge sys_clk) begin
	mem_adr0 <= soc_builder_csr_bankarray_adr;
end
assign soc_builder_csr_bankarray_dat_r = mem[mem_adr0];


//------------------------------------------------------------------------------
// Memory storage: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First  | Write-Granularity: 10 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage[0:15];
reg [9:0] storage_dat0;
reg [9:0] storage_dat1;
always @(posedge sys_clk) begin
	if (soc_basesoc_uart_tx_fifo_wrport_we)
		storage[soc_basesoc_uart_tx_fifo_wrport_adr] <= soc_basesoc_uart_tx_fifo_wrport_dat_w;
	storage_dat0 <= storage[soc_basesoc_uart_tx_fifo_wrport_adr];
end
always @(posedge sys_clk) begin
	if (soc_basesoc_uart_tx_fifo_rdport_re)
		storage_dat1 <= storage[soc_basesoc_uart_tx_fifo_rdport_adr];
end
assign soc_basesoc_uart_tx_fifo_wrport_dat_r = storage_dat0;
assign soc_basesoc_uart_tx_fifo_rdport_dat_r = storage_dat1;


//------------------------------------------------------------------------------
// Memory storage_1: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First  | Write-Granularity: 10 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage_1[0:15];
reg [9:0] storage_1_dat0;
reg [9:0] storage_1_dat1;
always @(posedge sys_clk) begin
	if (soc_basesoc_uart_rx_fifo_wrport_we)
		storage_1[soc_basesoc_uart_rx_fifo_wrport_adr] <= soc_basesoc_uart_rx_fifo_wrport_dat_w;
	storage_1_dat0 <= storage_1[soc_basesoc_uart_rx_fifo_wrport_adr];
end
always @(posedge sys_clk) begin
	if (soc_basesoc_uart_rx_fifo_rdport_re)
		storage_1_dat1 <= storage_1[soc_basesoc_uart_rx_fifo_rdport_adr];
end
assign soc_basesoc_uart_rx_fifo_wrport_dat_r = storage_1_dat0;
assign soc_basesoc_uart_rx_fifo_rdport_dat_r = storage_1_dat1;


FDCE FDCE(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_crg_reset),
	.Q(soc_builder_basesoc_reset0)
);

FDCE FDCE_1(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset0),
	.Q(soc_builder_basesoc_reset1)
);

FDCE FDCE_2(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset1),
	.Q(soc_builder_basesoc_reset2)
);

FDCE FDCE_3(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset2),
	.Q(soc_builder_basesoc_reset3)
);

FDCE FDCE_4(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset3),
	.Q(soc_builder_basesoc_reset4)
);

FDCE FDCE_5(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset4),
	.Q(soc_builder_basesoc_reset5)
);

FDCE FDCE_6(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset5),
	.Q(soc_builder_basesoc_reset6)
);

FDCE FDCE_7(
	.C(soc_crg_clkin),
	.CE(1'd1),
	.CLR(1'd0),
	.D(soc_builder_basesoc_reset6),
	.Q(soc_builder_basesoc_reset7)
);

PLLE2_ADV #(
	.CLKFBOUT_MULT(4'd12),
	.CLKIN1_PERIOD(8.0),
	.CLKOUT0_DIVIDE(4'd15),
	.CLKOUT0_PHASE(1'd0),
	.DIVCLK_DIVIDE(1'd1),
	.REF_JITTER1(0.01),
	.STARTUP_WAIT("FALSE")
) PLLE2_ADV (
	.CLKFBIN(soc_builder_basesoc_pll_fb),
	.CLKIN1(soc_crg_clkin),
	.PWRDWN(soc_crg_power_down),
	.RST(soc_builder_basesoc_reset7),
	.CLKFBOUT(soc_builder_basesoc_pll_fb),
	.CLKOUT0(soc_crg_clkout),
	.LOCKED(soc_crg_locked)
);

VexRiscv VexRiscv(
	.CfuPlugin_bus_cmd_ready(soc_basesoc_vexriscv_cfu_bus_cmd_ready),
	.CfuPlugin_bus_rsp_payload_outputs_0(soc_basesoc_vexriscv_cfu_bus_rsp_payload_outputs_0),
	.CfuPlugin_bus_rsp_valid(soc_basesoc_vexriscv_cfu_bus_rsp_valid),
	.clk(sys_clk),
	.dBusWishbone_ACK(soc_basesoc_dbus_ack),
	.dBusWishbone_DAT_MISO(soc_basesoc_dbus_dat_r),
	.dBusWishbone_ERR(soc_basesoc_dbus_err),
	.externalInterruptArray(soc_basesoc_interrupt),
	.externalResetVector(soc_basesoc_vexriscv),
	.iBusWishbone_ACK(soc_basesoc_ibus_ack),
	.iBusWishbone_DAT_MISO(soc_basesoc_ibus_dat_r),
	.iBusWishbone_ERR(soc_basesoc_ibus_err),
	.reset((sys_rst | soc_basesoc_reset)),
	.softwareInterrupt(1'd0),
	.timerInterrupt(1'd0),
	.CfuPlugin_bus_cmd_payload_function_id(soc_basesoc_vexriscv_cfu_bus_cmd_payload_function_id),
	.CfuPlugin_bus_cmd_payload_inputs_0(soc_basesoc_vexriscv_cfu_bus_cmd_payload_inputs_0),
	.CfuPlugin_bus_cmd_payload_inputs_1(soc_basesoc_vexriscv_cfu_bus_cmd_payload_inputs_1),
	.CfuPlugin_bus_cmd_valid(soc_basesoc_vexriscv_cfu_bus_cmd_valid),
	.CfuPlugin_bus_rsp_ready(soc_basesoc_vexriscv_cfu_bus_rsp_ready),
	.dBusWishbone_ADR(soc_basesoc_dbus_adr),
	.dBusWishbone_BTE(soc_basesoc_dbus_bte),
	.dBusWishbone_CTI(soc_basesoc_dbus_cti),
	.dBusWishbone_CYC(soc_basesoc_dbus_cyc),
	.dBusWishbone_DAT_MOSI(soc_basesoc_dbus_dat_w),
	.dBusWishbone_SEL(soc_basesoc_dbus_sel),
	.dBusWishbone_STB(soc_basesoc_dbus_stb),
	.dBusWishbone_WE(soc_basesoc_dbus_we),
	.iBusWishbone_ADR(soc_basesoc_ibus_adr),
	.iBusWishbone_BTE(soc_basesoc_ibus_bte),
	.iBusWishbone_CTI(soc_basesoc_ibus_cti),
	.iBusWishbone_CYC(soc_basesoc_ibus_cyc),
	.iBusWishbone_DAT_MOSI(soc_basesoc_ibus_dat_w),
	.iBusWishbone_SEL(soc_basesoc_ibus_sel),
	.iBusWishbone_STB(soc_basesoc_ibus_stb),
	.iBusWishbone_WE(soc_basesoc_ibus_we)
);

Cfu Cfu(
	.clk(sys_clk),
	.cmd_payload_function_id(soc_basesoc_vexriscv_cfu_bus_cmd_payload_function_id),
	.cmd_payload_inputs_0(soc_basesoc_vexriscv_cfu_bus_cmd_payload_inputs_0),
	.cmd_payload_inputs_1(soc_basesoc_vexriscv_cfu_bus_cmd_payload_inputs_1),
	.cmd_valid(soc_basesoc_vexriscv_cfu_bus_cmd_valid),
	.reset(sys_rst),
	.rsp_ready(soc_basesoc_vexriscv_cfu_bus_rsp_ready),
	.cmd_ready(soc_basesoc_vexriscv_cfu_bus_cmd_ready),
	.rsp_payload_outputs_0(soc_basesoc_vexriscv_cfu_bus_rsp_payload_outputs_0),
	.rsp_valid(soc_basesoc_vexriscv_cfu_bus_rsp_valid),
	.to_reconfig(to_reconfig),
	.configure_to(configure_to),
	.decouple_status(decouple_status),
	.decouple(decouple)
);

(* ars_ff1 = "true", async_reg = "true" *) FDPE #(
	.INIT(1'd1)
) FDPE (
	.C(sys_clk),
	.CE(1'd1),
	.D(1'd0),
	.PRE(soc_builder_xilinxasyncresetsynchronizerimpl),
	.Q(soc_builder_xilinxasyncresetsynchronizerimpl_rst_meta)
);

(* ars_ff2 = "true", async_reg = "true" *) FDPE #(
	.INIT(1'd1)
) FDPE_1 (
	.C(sys_clk),
	.CE(1'd1),
	.D(soc_builder_xilinxasyncresetsynchronizerimpl_rst_meta),
	.PRE(soc_builder_xilinxasyncresetsynchronizerimpl),
	.Q(sys_rst)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2025-11-04 13:44:47.
//------------------------------------------------------------------------------
