
####################################################################################
# Generated by Vivado 2023.2 built on 'Fri Oct 13 20:13:54 MDT 2023' by 'xbuild'
# Command Used: write_xdc ./Sources/xdc/top_all.xdc
####################################################################################


####################################################################################
# Constraints from file : 'top_io_a7100.xdc'
####################################################################################

####################################################################################
#///////////////////////////////////////////////////////////////////////////////
#// Copyright (c) 2005-2020 Xilinx, Inc.
#// This design is confidential and proprietary of Xilinx, Inc.
#// All Rights Reserved.
#///////////////////////////////////////////////////////////////////////////////
#//   ____  ____
#//  /   /\/   /
#// /___/  \  /   Vendor: Xilinx
#// \   \   \/    Version: 2020.1
#//  \   \        Application: Dynamic Function eXchange
#//  /   /        Filename: top_io_a7100.xdc
#// /___/   /\    Date Last Modified: 14 FEB 2020
#// \   \  / #//  \___\/\___ #// Device:
#// Design Name: led_shift_count
#// Purpose: Dynamic Function eXchange Tutorial
#///////////////////////////////////////////////////////////////////////////////

###############################################################################
# User Time Names / User Time Groups / Time Specs
###############################################################################
create_clock -period 5.000 -name clk_p [get_ports clk]

#set configuration voltage
set_property CONFIG_VOLTAGE 2.5 [current_design]
set_property CFGBVS VCCO [current_design]

#-----------------------------------
# LED LOCs
#    LED[0-3] shift
#    LED[4-7] count
#-----------------------------------
#Net shift_out[0] LOC=AB8; # GPIO_LED0_LS on Bank33 (VCC1V5 1.5 volt)
set_property PACKAGE_PIN H5 [get_ports {shift_out[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {shift_out[0]}]

# GPIO_LED1_LS on Bank33 (VCC1V5 1.5 volt)
set_property PACKAGE_PIN J5 [get_ports {shift_out[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {shift_out[1]}]

# GPIO_LED2_LS on Bank33 (VCC1V5 1.5 volt)
set_property PACKAGE_PIN T9 [get_ports {shift_out[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {shift_out[2]}]

# GPIO_LED3_LS on Bank33 (VCC1V5 1.5 volt)
set_property PACKAGE_PIN T10 [get_ports {shift_out[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {shift_out[3]}]

# GPIO_LED4_LS on Bank13 (VADJ 2.5 volt)
set_property PACKAGE_PIN F6 [get_ports {count_out[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {count_out[3]}]

# GPIO_LED5_LS on Bank17 (VADJ 2.5 volt)
set_property PACKAGE_PIN J4 [get_ports {count_out[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {count_out[2]}]

# GPIO_LED6_LS on Bank17 (VADJ 2.5 volt)
set_property PACKAGE_PIN J2 [get_ports {count_out[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {count_out[1]}]

# GPIO_LED7_LS on Bank18 (VADJ 2.5 volt)
set_property PACKAGE_PIN H6 [get_ports {count_out[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {count_out[0]}]


# For Programable Clock Source over SMA
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS15 [get_ports clk]

#-----------------------------------
# push buttons LOCs
#-----------------------------------
# Reset Button on Switch SW5 "Center Button"
# GPIO_SW_C on Bank18 (VADJ 2.5 volt)
set_property PACKAGE_PIN D9 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]


#-----------------------------------
# End
#-----------------------------------


# User Generated physical constraints 

create_pblock pblock_inst_count
add_cells_to_pblock [get_pblocks pblock_inst_count] [get_cells -quiet [list inst_count]]
resize_pblock [get_pblocks pblock_inst_count] -add {SLICE_X8Y100:SLICE_X15Y149}
resize_pblock [get_pblocks pblock_inst_count] -add {DSP48_X0Y40:DSP48_X0Y59}
resize_pblock [get_pblocks pblock_inst_count] -add {RAMB18_X0Y40:RAMB18_X0Y59}
resize_pblock [get_pblocks pblock_inst_count] -add {RAMB36_X0Y20:RAMB36_X0Y29}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_inst_count]

# User Generated miscellaneous constraints 


# User Generated physical constraints 

create_pblock pblock_inst_shift
add_cells_to_pblock [get_pblocks pblock_inst_shift] [get_cells -quiet [list inst_shift]]
resize_pblock [get_pblocks pblock_inst_shift] -add {SLICE_X68Y100:SLICE_X77Y149}
resize_pblock [get_pblocks pblock_inst_shift] -add {RAMB18_X2Y40:RAMB18_X2Y59}
resize_pblock [get_pblocks pblock_inst_shift] -add {RAMB36_X2Y20:RAMB36_X2Y29}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_inst_shift]

# User Generated miscellaneous constraints 


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
