# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jsp/Storage/CFU_PYNQ_FIles/CFU_SRC/pynq_z2/pynq_z2/arunQAFDHGDZXVNBDXG_gae.srcs/sources_1/ip/cfu_decoupler/cfu_decoupler.xci
# IP: The module: 'cfu_decoupler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jsp/Storage/CFU_PYNQ_FIles/CFU_SRC/pynq_z2/pynq_z2/arunQAFDHGDZXVNBDXG_gae.gen/sources_1/ip/cfu_decoupler/cfu_decoupler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfu_decoupler'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jsp/Storage/CFU_PYNQ_FIles/CFU_SRC/pynq_z2/pynq_z2/arunQAFDHGDZXVNBDXG_gae.srcs/sources_1/ip/cfu_decoupler/cfu_decoupler.xci
# IP: The module: 'cfu_decoupler' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jsp/Storage/CFU_PYNQ_FIles/CFU_SRC/pynq_z2/pynq_z2/arunQAFDHGDZXVNBDXG_gae.gen/sources_1/ip/cfu_decoupler/cfu_decoupler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfu_decoupler'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
