# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jsp/Storage/CFU-Playground/soc/build/digilent_arty.example_cfu/gateware/digilent_arty.srcs/sources_1/ip/dfx_decoupler_0/dfx_decoupler_0.xci
# IP: The module: 'dfx_decoupler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jsp/Storage/CFU-Playground/soc/build/digilent_arty.example_cfu/gateware/digilent_arty.gen/sources_1/ip/dfx_decoupler_0/dfx_decoupler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_decoupler_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jsp/Storage/CFU-Playground/soc/build/digilent_arty.example_cfu/gateware/digilent_arty.srcs/sources_1/ip/dfx_decoupler_0/dfx_decoupler_0.xci
# IP: The module: 'dfx_decoupler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jsp/Storage/CFU-Playground/soc/build/digilent_arty.example_cfu/gateware/digilent_arty.gen/sources_1/ip/dfx_decoupler_0/dfx_decoupler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_decoupler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
