
---------------------------------------------------------------------------
--
--  (c) Copyright 2013-2023 AMD, Inc. All rights reserved.
--
--  This file contains confidential and proprietary information
--  of AMD, Inc. and is protected under U.S. and
--  international copyright and other intellectual property
--  laws.
--
--  DISCLAIMER
--  This disclaimer is not a license and does not grant any
--  rights to the materials distributed herewith. Except as
--  otherwise provided in a valid license issued to you by
--  AMD, and to the maximum extent permitted by applicable
--  law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
--  WITH ALL FAULTS, AND AMD HEREBY DISCLAIMS ALL WARRANTIES
--  AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
--  BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
--  INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
--  (2) AMD shall not be liable (whether in contract or tort,
--  including negligence, or under any other theory of
--  liability) for any loss or damage of any kind or nature
--  related to, arising under or in connection with these
--  materials, including for any direct, or any indirect,
--  special, incidental, or consequential loss or damage
--  (including loss of data, profits, goodwill, or any type of
--  loss or damage suffered as a result of any action brought
--  by a third party) even if such damage or loss was
--  reasonably foreseeable or AMD had been advised of the
--  possibility of the same.
--
--  CRITICAL APPLICATIONS
--  AMD products are not designed or intended to be fail-
--  safe, or for use in any application requiring fail-safe
--  performance, such as life-support or safety devices or
--  systems, Class III medical devices, nuclear facilities,
--  applications related to the deployment of airbags, or any
--  other applications that could lead to death, personal
--  injury, or severe property or environmental damage
--  (individually and collectively, "Critical
--  Applications"). Customer assumes the sole risk and
--  liability of any use of AMD products in Critical
--  Applications, subject only to applicable laws and
--  regulations governing limitations on product liability.
--
--  THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
--  PART OF THIS FILE AT ALL TIMES.
--
---------------------------------------------------------------------------
-- Description:
-- This is an example testbench for the dfx_decoupler IP core.
-- The testbench has been generated by Vivado to accompany the IP core
-- instance you have generated.
--
-- This testbench is for demonstration purposes only.  See note below for
-- instructions on how to use it with the netlist created for your core.
--
-- See the dfx_decoupler product guide for further information
-- about this core.
--
---------------------------------------------------------------------------
-- Using this testbench
--
-- This testbench instantiates your generated dfx_decoupler core
-- instance named "cfu_decoupler".
--
-- Use Vivado's Run Simulation flow to run this testbench.  See the Vivado
-- documentation for details.
---------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;

library xil_defaultlib;

entity tb_cfu_decoupler is
end tb_cfu_decoupler;
 
architecture tb of tb_cfu_decoupler is

  -- Overall simulation phase control enumerated type and signal
  type t_sim_phase is (phase_pass_through,     -- Signals passing through the decoupler aren't decoupled
                       phase_in_transition,    -- Decoupling has changed but don't check; Give some time for the change to take effect
                       phase_decoupled         -- Signals passing through the decoupler are decoupled 
                       );
  signal sim_phase : t_sim_phase := phase_pass_through;

  constant CLOCK_PERIOD : time := 100 ns;
  signal clk: std_logic := '0'; 

  -- ---------------------------------------------------------------
  -- SIGNAL STATUS
  -- ---------------------------------------------------------------
  signal decouple_status: std_logic;

  -- ---------------------------------------------------------------
  -- SIGNAL CONTROL
  -- ---------------------------------------------------------------
  signal decouple : std_logic := '0';
  signal  s_cfu_inputs_cmd_valid : std_logic_vector(0 downto 0);
  signal rp_cfu_inputs_cmd_valid : std_logic_vector(0 downto 0);
  signal  s_cfu_inputs_cmd_payload_function_id : std_logic_vector(0 downto 0);
  signal rp_cfu_inputs_cmd_payload_function_id : std_logic_vector(0 downto 0);
  signal  s_cfu_inputs_cmd_payload_inputs_0 : std_logic_vector(9 downto 0);
  signal rp_cfu_inputs_cmd_payload_inputs_0 : std_logic_vector(9 downto 0);
  signal  s_cfu_inputs_cmd_payload_inputs_1 : std_logic_vector(31 downto 0);
  signal rp_cfu_inputs_cmd_payload_inputs_1 : std_logic_vector(31 downto 0);
  signal  s_cfu_inputs_rsp_ready : std_logic_vector(31 downto 0);
  signal rp_cfu_inputs_rsp_ready : std_logic_vector(31 downto 0);
  signal  s_cfu_inputs_reset : std_logic_vector(0 downto 0);
  signal rp_cfu_inputs_reset : std_logic_vector(0 downto 0);
  signal  s_cfu_inputs_clk : std_logic_vector(0 downto 0);
  signal rp_cfu_inputs_clk : std_logic_vector(0 downto 0);
  signal  s_cfu_output_cmd_ready : std_logic_vector(0 downto 0);
  signal rp_cfu_output_cmd_ready : std_logic_vector(0 downto 0);
  signal  s_cfu_output_rsp_valid : std_logic_vector(0 downto 0);
  signal rp_cfu_output_rsp_valid : std_logic_vector(0 downto 0);
  signal  s_cfu_output_rsp_payload_outputs_0 : std_logic_vector(31 downto 0);
  signal rp_cfu_output_rsp_payload_outputs_0 : std_logic_vector(31 downto 0);
  signal  s_cfu_output_cfu_id : std_logic_vector(2 downto 0);
  signal rp_cfu_output_cfu_id : std_logic_vector(2 downto 0);
  signal one  : std_logic:= '1';
  signal zero : std_logic:= '0';

begin
  dut : entity xil_defaultlib.cfu_decoupler
    port map (
      
      -- ---------------------------------------------------------------
      -- SIGNAL STATUS
      -- ---------------------------------------------------------------
      decouple_status => decouple_status,
      
      -- ---------------------------------------------------------------
      -- SIGNAL CONTROL
      -- ---------------------------------------------------------------
      decouple => decouple,
      
      -- ---------------------------------------------------------------
      -- Interface      = cfu_inputs
      -- vlnv           = undef
      -- mode           = slave
      -- static_mode    = slave
      -- cdc_stages     = 0
      -- ---------------------------------------------------------------
      s_cfu_inputs_cmd_valid  =>  s_cfu_inputs_cmd_valid,
      rp_cfu_inputs_cmd_valid => rp_cfu_inputs_cmd_valid,
      s_cfu_inputs_cmd_payload_function_id  =>  s_cfu_inputs_cmd_payload_function_id,
      rp_cfu_inputs_cmd_payload_function_id => rp_cfu_inputs_cmd_payload_function_id,
      s_cfu_inputs_cmd_payload_inputs_0  =>  s_cfu_inputs_cmd_payload_inputs_0,
      rp_cfu_inputs_cmd_payload_inputs_0 => rp_cfu_inputs_cmd_payload_inputs_0,
      s_cfu_inputs_cmd_payload_inputs_1  =>  s_cfu_inputs_cmd_payload_inputs_1,
      rp_cfu_inputs_cmd_payload_inputs_1 => rp_cfu_inputs_cmd_payload_inputs_1,
      s_cfu_inputs_rsp_ready  =>  s_cfu_inputs_rsp_ready,
      rp_cfu_inputs_rsp_ready => rp_cfu_inputs_rsp_ready,
      s_cfu_inputs_reset  =>  s_cfu_inputs_reset,
      rp_cfu_inputs_reset => rp_cfu_inputs_reset,
      s_cfu_inputs_clk  =>  s_cfu_inputs_clk,
      rp_cfu_inputs_clk => rp_cfu_inputs_clk,
      
      -- ---------------------------------------------------------------
      -- Interface      = cfu_output
      -- vlnv           = undef
      -- mode           = master
      -- static_mode    = master
      -- cdc_stages     = 0
      -- ---------------------------------------------------------------
      s_cfu_output_cmd_ready  =>  s_cfu_output_cmd_ready,
      rp_cfu_output_cmd_ready => rp_cfu_output_cmd_ready,
      s_cfu_output_rsp_valid  =>  s_cfu_output_rsp_valid,
      rp_cfu_output_rsp_valid => rp_cfu_output_rsp_valid,
      s_cfu_output_rsp_payload_outputs_0  =>  s_cfu_output_rsp_payload_outputs_0,
      rp_cfu_output_rsp_payload_outputs_0 => rp_cfu_output_rsp_payload_outputs_0,
      s_cfu_output_cfu_id  =>  s_cfu_output_cfu_id,
      rp_cfu_output_cfu_id => rp_cfu_output_cfu_id
    );

  clock_gen : process
  begin
    clk <= '0';
    wait for CLOCK_PERIOD;
    loop
      clk <= '0';
      wait for CLOCK_PERIOD/2;
      clk <= '1';
      wait for CLOCK_PERIOD/2;
    end loop;
  end process clock_gen;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_cmd_valid
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_cmd_valid_driver : process (clk)
    variable v_data : unsigned(1-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_cmd_valid <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_cmd_valid_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_cmd_valid_checker : process (clk)
    variable v_expected_data : unsigned(1-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_cmd_valid ) then
          report "cfu_inputs_cmd_valid mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 1) /= unsigned(rp_cfu_inputs_cmd_valid) then
          report "cfu_inputs_cmd_valid mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_cmd_valid_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_cmd_payload_function_id
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_cmd_payload_function_id_driver : process (clk)
    variable v_data : unsigned(1-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_cmd_payload_function_id <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_cmd_payload_function_id_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_cmd_payload_function_id_checker : process (clk)
    variable v_expected_data : unsigned(1-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_cmd_payload_function_id ) then
          report "cfu_inputs_cmd_payload_function_id mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 1) /= unsigned(rp_cfu_inputs_cmd_payload_function_id) then
          report "cfu_inputs_cmd_payload_function_id mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_cmd_payload_function_id_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_cmd_payload_inputs_0
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_cmd_payload_inputs_0_driver : process (clk)
    variable v_data : unsigned(10-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_cmd_payload_inputs_0 <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 10);
    end if;
  end process p_cfu_inputs_cmd_payload_inputs_0_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_cmd_payload_inputs_0_checker : process (clk)
    variable v_expected_data : unsigned(10-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_cmd_payload_inputs_0 ) then
          report "cfu_inputs_cmd_payload_inputs_0 mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 10) /= unsigned(rp_cfu_inputs_cmd_payload_inputs_0) then
          report "cfu_inputs_cmd_payload_inputs_0 mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 10);
    end if;
  end process p_cfu_inputs_cmd_payload_inputs_0_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_cmd_payload_inputs_1
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_cmd_payload_inputs_1_driver : process (clk)
    variable v_data : unsigned(32-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_cmd_payload_inputs_1 <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 32);
    end if;
  end process p_cfu_inputs_cmd_payload_inputs_1_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_cmd_payload_inputs_1_checker : process (clk)
    variable v_expected_data : unsigned(32-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_cmd_payload_inputs_1 ) then
          report "cfu_inputs_cmd_payload_inputs_1 mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 32) /= unsigned(rp_cfu_inputs_cmd_payload_inputs_1) then
          report "cfu_inputs_cmd_payload_inputs_1 mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 32);
    end if;
  end process p_cfu_inputs_cmd_payload_inputs_1_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_rsp_ready
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_rsp_ready_driver : process (clk)
    variable v_data : unsigned(32-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_rsp_ready <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 32);
    end if;
  end process p_cfu_inputs_rsp_ready_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_rsp_ready_checker : process (clk)
    variable v_expected_data : unsigned(32-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_rsp_ready ) then
          report "cfu_inputs_rsp_ready mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 32) /= unsigned(rp_cfu_inputs_rsp_ready) then
          report "cfu_inputs_rsp_ready mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 32);
    end if;
  end process p_cfu_inputs_rsp_ready_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_reset
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_reset_driver : process (clk)
    variable v_data : unsigned(1-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_reset <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_reset_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_reset_checker : process (clk)
    variable v_expected_data : unsigned(1-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_reset ) then
          report "cfu_inputs_reset mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 1) /= unsigned(rp_cfu_inputs_reset) then
          report "cfu_inputs_reset mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_reset_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_inputs_clk
  -- ------------------------------------------------------------------------------------
  p_cfu_inputs_clk_driver : process (clk)
    variable v_data : unsigned(1-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        s_cfu_inputs_clk <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_clk_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_inputs_clk_checker : process (clk)
    variable v_expected_data : unsigned(1-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( rp_cfu_inputs_clk ) then
          report "cfu_inputs_clk mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 1) /= unsigned(rp_cfu_inputs_clk) then
          report "cfu_inputs_clk mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_inputs_clk_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_output_cmd_ready
  -- ------------------------------------------------------------------------------------
  p_cfu_output_cmd_ready_driver : process (clk)
    variable v_data : unsigned(1-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        rp_cfu_output_cmd_ready <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_output_cmd_ready_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_output_cmd_ready_checker : process (clk)
    variable v_expected_data : unsigned(1-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( s_cfu_output_cmd_ready ) then
          report "cfu_output_cmd_ready mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 1) /= unsigned(s_cfu_output_cmd_ready) then
          report "cfu_output_cmd_ready mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_output_cmd_ready_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_output_rsp_valid
  -- ------------------------------------------------------------------------------------
  p_cfu_output_rsp_valid_driver : process (clk)
    variable v_data : unsigned(1-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        rp_cfu_output_rsp_valid <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_output_rsp_valid_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_output_rsp_valid_checker : process (clk)
    variable v_expected_data : unsigned(1-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( s_cfu_output_rsp_valid ) then
          report "cfu_output_rsp_valid mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 1) /= unsigned(s_cfu_output_rsp_valid) then
          report "cfu_output_rsp_valid mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 1);
    end if;
  end process p_cfu_output_rsp_valid_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_output_rsp_payload_outputs_0
  -- ------------------------------------------------------------------------------------
  p_cfu_output_rsp_payload_outputs_0_driver : process (clk)
    variable v_data : unsigned(32-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        rp_cfu_output_rsp_payload_outputs_0 <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 32);
    end if;
  end process p_cfu_output_rsp_payload_outputs_0_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_output_rsp_payload_outputs_0_checker : process (clk)
    variable v_expected_data : unsigned(32-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( s_cfu_output_rsp_payload_outputs_0 ) then
          report "cfu_output_rsp_payload_outputs_0 mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 32) /= unsigned(s_cfu_output_rsp_payload_outputs_0) then
          report "cfu_output_rsp_payload_outputs_0 mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 32);
    end if;
  end process p_cfu_output_rsp_payload_outputs_0_checker;

  -- ------------------------------------------------------------------------------------
  -- Drive and Check cfu_output_cfu_id
  -- ------------------------------------------------------------------------------------
  p_cfu_output_cfu_id_driver : process (clk)
    variable v_data : unsigned(3-1 downto 0) := (others => '0');
  begin
    if rising_edge(clk) then
        rp_cfu_output_cfu_id <= std_logic_vector(v_data);
       v_data := v_data + to_unsigned(1, 3);
    end if;
  end process p_cfu_output_cfu_id_driver;



  -- This TB works by incrementing the input data and checking it on the falling edge.
  -- When an interface is registered, we need to check "data - 1" unless it's a clock signal which 
  -- doesn't get registered. It will with AXIMM and AXIS as they are protocol aware and they don't 
  -- just pass data through with a simple delay.  This TB is meant to be a simple example of how to 
  -- instantiate and use the core, so it doesn't check when the interface is registered
  --
  -- Signals decoupled via a clock buffer also aren't be checked here as decouple doesn't take immediate effect
  -- when BUFGCEs are used.  The code required to predict when decouple applies is too complex for this demonstration 
  -- testbench.  See the Product Guide for more information

  p_cfu_output_cfu_id_checker : process (clk)
    variable v_expected_data : unsigned(3-1 downto 0) := (others => '0');
    constant is_decoupled: std_logic := '1';
  begin
    if falling_edge(clk) then
      if sim_phase = phase_pass_through or is_decoupled = '0' then
        if v_expected_data /= unsigned( s_cfu_output_cfu_id ) then
          report "cfu_output_cfu_id mismatch in passthrough mode" severity ERROR;
        end if; 
      elsif sim_phase = phase_decoupled then
        if resize(x"0", 3) /= unsigned(s_cfu_output_cfu_id) then
          report "cfu_output_cfu_id mismatch in decouple mode" severity ERROR;
        end if; 
      end if;
      v_expected_data := v_expected_data + to_unsigned(1, 3);
    end if;
  end process p_cfu_output_cfu_id_checker;


  -----------------------------------------------------------------------
  -- Simulation control
  -- Run a series of demonstrations, each in a separate test phase
  -- This process controls all other stimuli processes
  -----------------------------------------------------------------------
  sim_control : process
  begin
    -- Drive simulation control synchronous to the rising edge of the clock
    wait until rising_edge(clk);

    -- -------------------------------------------------------
    -- Start with decoupling off
    -- -------------------------------------------------------
    sim_phase <= phase_pass_through;
    wait for 120 * CLOCK_PERIOD;

    -- -------------------------------------------------------
    -- Turn decoupling on
    -- -------------------------------------------------------
    sim_phase <= phase_in_transition;

    -- Using Signal Control interface
    decouple <= '1';
    wait for 10 * CLOCK_PERIOD;

    wait for 10 * CLOCK_PERIOD;
    sim_phase <= phase_decoupled;
    wait for 120 * CLOCK_PERIOD;

    -- -------------------------------------------------------
    -- Turn decoupling off
    -- -------------------------------------------------------
    sim_phase <= phase_in_transition;

    -- Using Signal Control interface
    decouple <= '0';
    wait for 10 * CLOCK_PERIOD;

    wait for 10 * CLOCK_PERIOD;

    sim_phase <= phase_pass_through;
    wait for 120 * CLOCK_PERIOD;

    -- End of simulation
    wait for CLOCK_PERIOD;
    report "Not a real failure. Test completed successfully." severity failure;
    wait;
  end process sim_control;

end tb;
