# This file is automatically generated.
# It contains HD.RECONFIGURABLE settings for all instances of partition_def.

set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == count || REF_NAME == count}]
set_property KEEP_HIERARCHY SOFT -quiet [get_cells -hier -filter {ORIG_REF_NAME == count || REF_NAME == count}]
set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == shift || REF_NAME == shift}]
set_property KEEP_HIERARCHY SOFT -quiet [get_cells -hier -filter {ORIG_REF_NAME == shift || REF_NAME == shift}]
