# This file is automatically generated.
# It contains HD.RECONFIGURABLE settings for all instances of partition_def.

set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == cfu_compute || REF_NAME == cfu_compute}]
set_property KEEP_HIERARCHY SOFT -quiet [get_cells -hier -filter {ORIG_REF_NAME == cfu_compute || REF_NAME == cfu_compute}]
