set_property SRC_FILE_INFO {cfile:/home/jsp/Storage/CFU_PYNQ_FIles/CFU_SRC/pynq_z2/pynq_z2/arunQAFDHGDZXVNBDXG_gae.srcs/constrs_1/imports/new/tul_pynq_z2.xdc rfile:../../../arunQAFDHGDZXVNBDXG_gae.srcs/constrs_1/imports/new/tul_pynq_z2.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jsp/Storage/CFU_PYNQ_FIles/CFU_SRC/pynq_z2/pynq_z2/arunQAFDHGDZXVNBDXG_gae.srcs/constrs_1/new/pblock.xdc rfile:../../../arunQAFDHGDZXVNBDXG_gae.srcs/constrs_1/new/pblock.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC H16 [get_ports {pl_clk}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y14 [get_ports {usb_uart_tx}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T11 [get_ports {usb_uart_rx}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R14 [get_ports {user_led0}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R14 [get_ports {user_led0}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P14 [get_ports {user_led1}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC N16 [get_ports {user_led2}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M14 [get_ports {user_led3}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_cfu_inst
add_cells_to_pblock [get_pblocks pblock_cfu_inst] [get_cells -quiet [list cfu_system/Cfu/cfu_inst]]
resize_pblock [get_pblocks pblock_cfu_inst] -add {SLICE_X34Y50:SLICE_X39Y99}
resize_pblock [get_pblocks pblock_cfu_inst] -add {DSP48_X2Y20:DSP48_X2Y39}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_cfu_inst]
set_property SNAPPING_MODE ON [get_pblocks pblock_cfu_inst]
